// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::projectile_kind_type::ProjectileKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ActiveProjectile {
    pub projectile_id: u64,
    pub shooter_id: u64,
    pub kind: ProjectileKind,
    pub pos_x: f32,
    pub pos_y: f32,
    pub pos_z: f32,
    pub vel_x: f32,
    pub vel_y: f32,
    pub vel_z: f32,
    pub gravity: f32,
    pub drag: f32,
    pub damage: f32,
    pub blast_radius: f32,
    pub start_tick: u64,
    pub lifetime: f32,
}

impl __sdk::InModule for ActiveProjectile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ActiveProjectile`.
///
/// Provides typed access to columns for query building.
pub struct ActiveProjectileCols {
    pub projectile_id: __sdk::__query_builder::Col<ActiveProjectile, u64>,
    pub shooter_id: __sdk::__query_builder::Col<ActiveProjectile, u64>,
    pub kind: __sdk::__query_builder::Col<ActiveProjectile, ProjectileKind>,
    pub pos_x: __sdk::__query_builder::Col<ActiveProjectile, f32>,
    pub pos_y: __sdk::__query_builder::Col<ActiveProjectile, f32>,
    pub pos_z: __sdk::__query_builder::Col<ActiveProjectile, f32>,
    pub vel_x: __sdk::__query_builder::Col<ActiveProjectile, f32>,
    pub vel_y: __sdk::__query_builder::Col<ActiveProjectile, f32>,
    pub vel_z: __sdk::__query_builder::Col<ActiveProjectile, f32>,
    pub gravity: __sdk::__query_builder::Col<ActiveProjectile, f32>,
    pub drag: __sdk::__query_builder::Col<ActiveProjectile, f32>,
    pub damage: __sdk::__query_builder::Col<ActiveProjectile, f32>,
    pub blast_radius: __sdk::__query_builder::Col<ActiveProjectile, f32>,
    pub start_tick: __sdk::__query_builder::Col<ActiveProjectile, u64>,
    pub lifetime: __sdk::__query_builder::Col<ActiveProjectile, f32>,
}

impl __sdk::__query_builder::HasCols for ActiveProjectile {
    type Cols = ActiveProjectileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ActiveProjectileCols {
            projectile_id: __sdk::__query_builder::Col::new(table_name, "projectile_id"),
            shooter_id: __sdk::__query_builder::Col::new(table_name, "shooter_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            pos_x: __sdk::__query_builder::Col::new(table_name, "pos_x"),
            pos_y: __sdk::__query_builder::Col::new(table_name, "pos_y"),
            pos_z: __sdk::__query_builder::Col::new(table_name, "pos_z"),
            vel_x: __sdk::__query_builder::Col::new(table_name, "vel_x"),
            vel_y: __sdk::__query_builder::Col::new(table_name, "vel_y"),
            vel_z: __sdk::__query_builder::Col::new(table_name, "vel_z"),
            gravity: __sdk::__query_builder::Col::new(table_name, "gravity"),
            drag: __sdk::__query_builder::Col::new(table_name, "drag"),
            damage: __sdk::__query_builder::Col::new(table_name, "damage"),
            blast_radius: __sdk::__query_builder::Col::new(table_name, "blast_radius"),
            start_tick: __sdk::__query_builder::Col::new(table_name, "start_tick"),
            lifetime: __sdk::__query_builder::Col::new(table_name, "lifetime"),
        }
    }
}

/// Indexed column accessor struct for the table `ActiveProjectile`.
///
/// Provides typed access to indexed columns for query building.
pub struct ActiveProjectileIxCols {
    pub projectile_id: __sdk::__query_builder::IxCol<ActiveProjectile, u64>,
}

impl __sdk::__query_builder::HasIxCols for ActiveProjectile {
    type IxCols = ActiveProjectileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ActiveProjectileIxCols {
            projectile_id: __sdk::__query_builder::IxCol::new(table_name, "projectile_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ActiveProjectile {}
