// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminSpawnNpcArgs {
    pub ai_type_str: String,
    pub count: u32,
}

impl From<AdminSpawnNpcArgs> for super::Reducer {
    fn from(args: AdminSpawnNpcArgs) -> Self {
        Self::AdminSpawnNpc {
            ai_type_str: args.ai_type_str,
            count: args.count,
        }
    }
}

impl __sdk::InModule for AdminSpawnNpcArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_spawn_npc`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_spawn_npc {
    /// Request that the remote module invoke the reducer `admin_spawn_npc` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_spawn_npc:admin_spawn_npc_then`] to run a callback after the reducer completes.
    fn admin_spawn_npc(&self, ai_type_str: String, count: u32) -> __sdk::Result<()> {
        self.admin_spawn_npc_then(ai_type_str, count, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_spawn_npc` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_spawn_npc_then(
        &self,
        ai_type_str: String,
        count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_spawn_npc for super::RemoteReducers {
    fn admin_spawn_npc_then(
        &self,
        ai_type_str: String,
        count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdminSpawnNpcArgs { ai_type_str, count }, callback)
    }
}
