// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminGodModeArgs {}

impl From<AdminGodModeArgs> for super::Reducer {
    fn from(args: AdminGodModeArgs) -> Self {
        Self::AdminGodMode
    }
}

impl __sdk::InModule for AdminGodModeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_god_mode`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_god_mode {
    /// Request that the remote module invoke the reducer `admin_god_mode` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_god_mode:admin_god_mode_then`] to run a callback after the reducer completes.
    fn admin_god_mode(&self) -> __sdk::Result<()> {
        self.admin_god_mode_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_god_mode` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_god_mode_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_god_mode for super::RemoteReducers {
    fn admin_god_mode_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdminGodModeArgs {}, callback)
    }
}
