// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminSetTimeArgs {
    pub time_of_day: f32,
}

impl From<AdminSetTimeArgs> for super::Reducer {
    fn from(args: AdminSetTimeArgs) -> Self {
        Self::AdminSetTime {
            time_of_day: args.time_of_day,
        }
    }
}

impl __sdk::InModule for AdminSetTimeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_set_time`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_set_time {
    /// Request that the remote module invoke the reducer `admin_set_time` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_set_time:admin_set_time_then`] to run a callback after the reducer completes.
    fn admin_set_time(&self, time_of_day: f32) -> __sdk::Result<()> {
        self.admin_set_time_then(time_of_day, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_set_time` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_set_time_then(
        &self,
        time_of_day: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_set_time for super::RemoteReducers {
    fn admin_set_time_then(
        &self,
        time_of_day: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdminSetTimeArgs { time_of_day }, callback)
    }
}
