// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminGiveItemArgs {
    pub item_type: String,
    pub amount: u32,
}

impl From<AdminGiveItemArgs> for super::Reducer {
    fn from(args: AdminGiveItemArgs) -> Self {
        Self::AdminGiveItem {
            item_type: args.item_type,
            amount: args.amount,
        }
    }
}

impl __sdk::InModule for AdminGiveItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_give_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_give_item {
    /// Request that the remote module invoke the reducer `admin_give_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_give_item:admin_give_item_then`] to run a callback after the reducer completes.
    fn admin_give_item(&self, item_type: String, amount: u32) -> __sdk::Result<()> {
        self.admin_give_item_then(item_type, amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_give_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_give_item_then(
        &self,
        item_type: String,
        amount: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_give_item for super::RemoteReducers {
    fn admin_give_item_then(
        &self,
        item_type: String,
        amount: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdminGiveItemArgs { item_type, amount }, callback)
    }
}
