// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CommandPeasantArgs {
    pub peasant_entity_id: u64,
    pub command_type: String,
    pub target_x: f32,
    pub target_y: f32,
    pub target_z: f32,
    pub target_id: u64,
}

impl From<CommandPeasantArgs> for super::Reducer {
    fn from(args: CommandPeasantArgs) -> Self {
        Self::CommandPeasant {
            peasant_entity_id: args.peasant_entity_id,
            command_type: args.command_type,
            target_x: args.target_x,
            target_y: args.target_y,
            target_z: args.target_z,
            target_id: args.target_id,
        }
    }
}

impl __sdk::InModule for CommandPeasantArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `command_peasant`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait command_peasant {
    /// Request that the remote module invoke the reducer `command_peasant` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`command_peasant:command_peasant_then`] to run a callback after the reducer completes.
    fn command_peasant(
        &self,
        peasant_entity_id: u64,
        command_type: String,
        target_x: f32,
        target_y: f32,
        target_z: f32,
        target_id: u64,
    ) -> __sdk::Result<()> {
        self.command_peasant_then(
            peasant_entity_id,
            command_type,
            target_x,
            target_y,
            target_z,
            target_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `command_peasant` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn command_peasant_then(
        &self,
        peasant_entity_id: u64,
        command_type: String,
        target_x: f32,
        target_y: f32,
        target_z: f32,
        target_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl command_peasant for super::RemoteReducers {
    fn command_peasant_then(
        &self,
        peasant_entity_id: u64,
        command_type: String,
        target_x: f32,
        target_y: f32,
        target_z: f32,
        target_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CommandPeasantArgs {
                peasant_entity_id,
                command_type,
                target_x,
                target_y,
                target_z,
                target_id,
            },
            callback,
        )
    }
}
