// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ConsumeItemArgs {
    pub item_name: String,
}

impl From<ConsumeItemArgs> for super::Reducer {
    fn from(args: ConsumeItemArgs) -> Self {
        Self::ConsumeItem {
            item_name: args.item_name,
        }
    }
}

impl __sdk::InModule for ConsumeItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `consume_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait consume_item {
    /// Request that the remote module invoke the reducer `consume_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`consume_item:consume_item_then`] to run a callback after the reducer completes.
    fn consume_item(&self, item_name: String) -> __sdk::Result<()> {
        self.consume_item_then(item_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `consume_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn consume_item_then(
        &self,
        item_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl consume_item for super::RemoteReducers {
    fn consume_item_then(
        &self,
        item_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ConsumeItemArgs { item_name }, callback)
    }
}
