// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DetonateExplosiveChargeArgs {
    pub pos_x: f32,
    pub pos_y: f32,
    pub pos_z: f32,
    pub power: f32,
    pub radius: f32,
}

impl From<DetonateExplosiveChargeArgs> for super::Reducer {
    fn from(args: DetonateExplosiveChargeArgs) -> Self {
        Self::DetonateExplosiveCharge {
            pos_x: args.pos_x,
            pos_y: args.pos_y,
            pos_z: args.pos_z,
            power: args.power,
            radius: args.radius,
        }
    }
}

impl __sdk::InModule for DetonateExplosiveChargeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `detonate_explosive_charge`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait detonate_explosive_charge {
    /// Request that the remote module invoke the reducer `detonate_explosive_charge` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`detonate_explosive_charge:detonate_explosive_charge_then`] to run a callback after the reducer completes.
    fn detonate_explosive_charge(
        &self,
        pos_x: f32,
        pos_y: f32,
        pos_z: f32,
        power: f32,
        radius: f32,
    ) -> __sdk::Result<()> {
        self.detonate_explosive_charge_then(pos_x, pos_y, pos_z, power, radius, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `detonate_explosive_charge` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn detonate_explosive_charge_then(
        &self,
        pos_x: f32,
        pos_y: f32,
        pos_z: f32,
        power: f32,
        radius: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl detonate_explosive_charge for super::RemoteReducers {
    fn detonate_explosive_charge_then(
        &self,
        pos_x: f32,
        pos_y: f32,
        pos_z: f32,
        power: f32,
        radius: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DetonateExplosiveChargeArgs {
                pos_x,
                pos_y,
                pos_z,
                power,
                radius,
            },
            callback,
        )
    }
}
