// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DropInventoryItemArgs {
    pub slot_index: u32,
    pub amount: u32,
}

impl From<DropInventoryItemArgs> for super::Reducer {
    fn from(args: DropInventoryItemArgs) -> Self {
        Self::DropInventoryItem {
            slot_index: args.slot_index,
            amount: args.amount,
        }
    }
}

impl __sdk::InModule for DropInventoryItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `drop_inventory_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait drop_inventory_item {
    /// Request that the remote module invoke the reducer `drop_inventory_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`drop_inventory_item:drop_inventory_item_then`] to run a callback after the reducer completes.
    fn drop_inventory_item(&self, slot_index: u32, amount: u32) -> __sdk::Result<()> {
        self.drop_inventory_item_then(slot_index, amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `drop_inventory_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn drop_inventory_item_then(
        &self,
        slot_index: u32,
        amount: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl drop_inventory_item for super::RemoteReducers {
    fn drop_inventory_item_then(
        &self,
        slot_index: u32,
        amount: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DropInventoryItemArgs { slot_index, amount }, callback)
    }
}
