// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Health {
    pub entity_id: u64,
    pub current: f32,
    pub max: f32,
}

impl __sdk::InModule for Health {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Health`.
///
/// Provides typed access to columns for query building.
pub struct HealthCols {
    pub entity_id: __sdk::__query_builder::Col<Health, u64>,
    pub current: __sdk::__query_builder::Col<Health, f32>,
    pub max: __sdk::__query_builder::Col<Health, f32>,
}

impl __sdk::__query_builder::HasCols for Health {
    type Cols = HealthCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HealthCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            current: __sdk::__query_builder::Col::new(table_name, "current"),
            max: __sdk::__query_builder::Col::new(table_name, "max"),
        }
    }
}

/// Indexed column accessor struct for the table `Health`.
///
/// Provides typed access to indexed columns for query building.
pub struct HealthIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<Health, u64>,
}

impl __sdk::__query_builder::HasIxCols for Health {
    type IxCols = HealthIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HealthIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Health {}
