// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HighFrequencyTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
}

impl __sdk::InModule for HighFrequencyTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HighFrequencyTimer`.
///
/// Provides typed access to columns for query building.
pub struct HighFrequencyTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<HighFrequencyTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<HighFrequencyTimer, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for HighFrequencyTimer {
    type Cols = HighFrequencyTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HighFrequencyTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `HighFrequencyTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct HighFrequencyTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<HighFrequencyTimer, u64>,
}

impl __sdk::__query_builder::HasIxCols for HighFrequencyTimer {
    type IxCols = HighFrequencyTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HighFrequencyTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for HighFrequencyTimer {}
