// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NavEvent {
    pub id: u64,
    pub min_x: f32,
    pub min_y: f32,
    pub min_z: f32,
    pub max_x: f32,
    pub max_y: f32,
    pub max_z: f32,
}

impl __sdk::InModule for NavEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NavEvent`.
///
/// Provides typed access to columns for query building.
pub struct NavEventCols {
    pub id: __sdk::__query_builder::Col<NavEvent, u64>,
    pub min_x: __sdk::__query_builder::Col<NavEvent, f32>,
    pub min_y: __sdk::__query_builder::Col<NavEvent, f32>,
    pub min_z: __sdk::__query_builder::Col<NavEvent, f32>,
    pub max_x: __sdk::__query_builder::Col<NavEvent, f32>,
    pub max_y: __sdk::__query_builder::Col<NavEvent, f32>,
    pub max_z: __sdk::__query_builder::Col<NavEvent, f32>,
}

impl __sdk::__query_builder::HasCols for NavEvent {
    type Cols = NavEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NavEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            min_x: __sdk::__query_builder::Col::new(table_name, "min_x"),
            min_y: __sdk::__query_builder::Col::new(table_name, "min_y"),
            min_z: __sdk::__query_builder::Col::new(table_name, "min_z"),
            max_x: __sdk::__query_builder::Col::new(table_name, "max_x"),
            max_y: __sdk::__query_builder::Col::new(table_name, "max_y"),
            max_z: __sdk::__query_builder::Col::new(table_name, "max_z"),
        }
    }
}

/// Indexed column accessor struct for the table `NavEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct NavEventIxCols {
    pub id: __sdk::__query_builder::IxCol<NavEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for NavEvent {
    type IxCols = NavEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NavEventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NavEvent {}
