// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::pet_stance_type::PetStance;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PetComponent {
    pub entity_id: u64,
    pub owner_id: u64,
    pub stance: PetStance,
}

impl __sdk::InModule for PetComponent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PetComponent`.
///
/// Provides typed access to columns for query building.
pub struct PetComponentCols {
    pub entity_id: __sdk::__query_builder::Col<PetComponent, u64>,
    pub owner_id: __sdk::__query_builder::Col<PetComponent, u64>,
    pub stance: __sdk::__query_builder::Col<PetComponent, PetStance>,
}

impl __sdk::__query_builder::HasCols for PetComponent {
    type Cols = PetComponentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PetComponentCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            owner_id: __sdk::__query_builder::Col::new(table_name, "owner_id"),
            stance: __sdk::__query_builder::Col::new(table_name, "stance"),
        }
    }
}

/// Indexed column accessor struct for the table `PetComponent`.
///
/// Provides typed access to indexed columns for query building.
pub struct PetComponentIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PetComponent, u64>,
    pub owner_id: __sdk::__query_builder::IxCol<PetComponent, u64>,
}

impl __sdk::__query_builder::HasIxCols for PetComponent {
    type IxCols = PetComponentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PetComponentIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            owner_id: __sdk::__query_builder::IxCol::new(table_name, "owner_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PetComponent {}
