// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::recipe_ingredient_type::RecipeIngredient;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RecipeDefinition {
    pub recipe_id: String,
    pub output_item: String,
    pub output_count: u32,
    pub required_station: String,
    pub requires_roof: bool,
    pub ingredients: Vec<RecipeIngredient>,
}

impl __sdk::InModule for RecipeDefinition {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RecipeDefinition`.
///
/// Provides typed access to columns for query building.
pub struct RecipeDefinitionCols {
    pub recipe_id: __sdk::__query_builder::Col<RecipeDefinition, String>,
    pub output_item: __sdk::__query_builder::Col<RecipeDefinition, String>,
    pub output_count: __sdk::__query_builder::Col<RecipeDefinition, u32>,
    pub required_station: __sdk::__query_builder::Col<RecipeDefinition, String>,
    pub requires_roof: __sdk::__query_builder::Col<RecipeDefinition, bool>,
    pub ingredients: __sdk::__query_builder::Col<RecipeDefinition, Vec<RecipeIngredient>>,
}

impl __sdk::__query_builder::HasCols for RecipeDefinition {
    type Cols = RecipeDefinitionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RecipeDefinitionCols {
            recipe_id: __sdk::__query_builder::Col::new(table_name, "recipe_id"),
            output_item: __sdk::__query_builder::Col::new(table_name, "output_item"),
            output_count: __sdk::__query_builder::Col::new(table_name, "output_count"),
            required_station: __sdk::__query_builder::Col::new(table_name, "required_station"),
            requires_roof: __sdk::__query_builder::Col::new(table_name, "requires_roof"),
            ingredients: __sdk::__query_builder::Col::new(table_name, "ingredients"),
        }
    }
}

/// Indexed column accessor struct for the table `RecipeDefinition`.
///
/// Provides typed access to indexed columns for query building.
pub struct RecipeDefinitionIxCols {
    pub recipe_id: __sdk::__query_builder::IxCol<RecipeDefinition, String>,
}

impl __sdk::__query_builder::HasIxCols for RecipeDefinition {
    type IxCols = RecipeDefinitionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RecipeDefinitionIxCols {
            recipe_id: __sdk::__query_builder::IxCol::new(table_name, "recipe_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RecipeDefinition {}
