// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ResourceNode {
    pub node_id: u64,
    pub node_type: String,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub chunk_x: i32,
    pub chunk_z: i32,
    pub health: u32,
    pub scale: f32,
    pub required_tool: String,
}

impl __sdk::InModule for ResourceNode {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ResourceNode`.
///
/// Provides typed access to columns for query building.
pub struct ResourceNodeCols {
    pub node_id: __sdk::__query_builder::Col<ResourceNode, u64>,
    pub node_type: __sdk::__query_builder::Col<ResourceNode, String>,
    pub x: __sdk::__query_builder::Col<ResourceNode, f32>,
    pub y: __sdk::__query_builder::Col<ResourceNode, f32>,
    pub z: __sdk::__query_builder::Col<ResourceNode, f32>,
    pub chunk_x: __sdk::__query_builder::Col<ResourceNode, i32>,
    pub chunk_z: __sdk::__query_builder::Col<ResourceNode, i32>,
    pub health: __sdk::__query_builder::Col<ResourceNode, u32>,
    pub scale: __sdk::__query_builder::Col<ResourceNode, f32>,
    pub required_tool: __sdk::__query_builder::Col<ResourceNode, String>,
}

impl __sdk::__query_builder::HasCols for ResourceNode {
    type Cols = ResourceNodeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ResourceNodeCols {
            node_id: __sdk::__query_builder::Col::new(table_name, "node_id"),
            node_type: __sdk::__query_builder::Col::new(table_name, "node_type"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            chunk_x: __sdk::__query_builder::Col::new(table_name, "chunk_x"),
            chunk_z: __sdk::__query_builder::Col::new(table_name, "chunk_z"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            scale: __sdk::__query_builder::Col::new(table_name, "scale"),
            required_tool: __sdk::__query_builder::Col::new(table_name, "required_tool"),
        }
    }
}

/// Indexed column accessor struct for the table `ResourceNode`.
///
/// Provides typed access to indexed columns for query building.
pub struct ResourceNodeIxCols {
    pub chunk_x: __sdk::__query_builder::IxCol<ResourceNode, i32>,
    pub chunk_z: __sdk::__query_builder::IxCol<ResourceNode, i32>,
    pub node_id: __sdk::__query_builder::IxCol<ResourceNode, u64>,
}

impl __sdk::__query_builder::HasIxCols for ResourceNode {
    type IxCols = ResourceNodeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ResourceNodeIxCols {
            chunk_x: __sdk::__query_builder::IxCol::new(table_name, "chunk_x"),
            chunk_z: __sdk::__query_builder::IxCol::new(table_name, "chunk_z"),
            node_id: __sdk::__query_builder::IxCol::new(table_name, "node_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ResourceNode {}
