// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RespawnBushTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub node_id: u64,
}

impl __sdk::InModule for RespawnBushTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RespawnBushTimer`.
///
/// Provides typed access to columns for query building.
pub struct RespawnBushTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<RespawnBushTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<RespawnBushTimer, __sdk::ScheduleAt>,
    pub node_id: __sdk::__query_builder::Col<RespawnBushTimer, u64>,
}

impl __sdk::__query_builder::HasCols for RespawnBushTimer {
    type Cols = RespawnBushTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RespawnBushTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            node_id: __sdk::__query_builder::Col::new(table_name, "node_id"),
        }
    }
}

/// Indexed column accessor struct for the table `RespawnBushTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct RespawnBushTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<RespawnBushTimer, u64>,
}

impl __sdk::__query_builder::HasIxCols for RespawnBushTimer {
    type IxCols = RespawnBushTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RespawnBushTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RespawnBushTimer {}
