// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::active_projectile_type::ActiveProjectile;
use super::projectile_kind_type::ProjectileKind;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `active_projectile`.
///
/// Obtain a handle from the [`ActiveProjectileTableAccess::active_projectile`] method on [`super::RemoteTables`],
/// like `ctx.db.active_projectile()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.active_projectile().on_insert(...)`.
pub struct ActiveProjectileTableHandle<'ctx> {
    imp: __sdk::TableHandle<ActiveProjectile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `active_projectile`.
pub struct ActiveProjectileTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ActiveProjectileTableAccessor {
    type Row = ActiveProjectile;
    type Handle<'db> = ActiveProjectileTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.active_projectile()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `active_projectile`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ActiveProjectileTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ActiveProjectileTableHandle`], which mediates access to the table `active_projectile`.
    fn active_projectile(&self) -> ActiveProjectileTableHandle<'_>;
}

impl ActiveProjectileTableAccess for super::RemoteTables {
    fn active_projectile(&self) -> ActiveProjectileTableHandle<'_> {
        ActiveProjectileTableHandle {
            imp: self.imp.get_table::<ActiveProjectile>("active_projectile"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ActiveProjectileInsertCallbackId(__sdk::CallbackId);
pub struct ActiveProjectileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ActiveProjectileTableHandle<'ctx> {
    type Row = ActiveProjectile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ActiveProjectile> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ActiveProjectileTableHandle<'ctx> {
    type Row = ActiveProjectile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ActiveProjectile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ActiveProjectileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveProjectileInsertCallbackId {
        ActiveProjectileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActiveProjectileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ActiveProjectileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveProjectileDeleteCallbackId {
        ActiveProjectileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActiveProjectileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ActiveProjectileTableHandle<'ctx> {
    type InsertCallbackId = ActiveProjectileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveProjectileInsertCallbackId {
        ActiveProjectileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActiveProjectileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ActiveProjectileTableHandle<'ctx> {
    type DeleteCallbackId = ActiveProjectileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveProjectileDeleteCallbackId {
        ActiveProjectileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActiveProjectileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ActiveProjectileUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ActiveProjectileTableHandle<'ctx> {
    type UpdateCallbackId = ActiveProjectileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ActiveProjectileUpdateCallbackId {
        ActiveProjectileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ActiveProjectileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ActiveProjectileTableHandle<'ctx> {
    type UpdateCallbackId = ActiveProjectileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ActiveProjectileUpdateCallbackId {
        ActiveProjectileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ActiveProjectileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `projectile_id` unique index on the table `active_projectile`,
/// which allows point queries on the field of the same name
/// via the [`ActiveProjectileProjectileIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.active_projectile().projectile_id().find(...)`.
pub struct ActiveProjectileProjectileIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ActiveProjectile, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ActiveProjectileTableHandle<'ctx> {
    /// Get a handle on the `projectile_id` unique index on the table `active_projectile`.
    pub fn projectile_id(&self) -> ActiveProjectileProjectileIdUnique<'ctx> {
        ActiveProjectileProjectileIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("projectile_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ActiveProjectileProjectileIdUnique<'ctx> {
    /// Find the subscribed row whose `projectile_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ActiveProjectile> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ActiveProjectile>("active_projectile");
    _table.add_unique_constraint::<u64>("projectile_id", |row| &row.projectile_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ActiveProjectile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ActiveProjectile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ActiveProjectile`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait active_projectileQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ActiveProjectile`.
    fn active_projectile(&self) -> __sdk::__query_builder::Table<ActiveProjectile>;
}

impl active_projectileQueryTableAccess for __sdk::QueryTableAccessor {
    fn active_projectile(&self) -> __sdk::__query_builder::Table<ActiveProjectile> {
        __sdk::__query_builder::Table::new("active_projectile")
    }
}
