// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminRandomizeWorldSeedArgs {}

impl From<AdminRandomizeWorldSeedArgs> for super::Reducer {
    fn from(args: AdminRandomizeWorldSeedArgs) -> Self {
        Self::AdminRandomizeWorldSeed
    }
}

impl __sdk::InModule for AdminRandomizeWorldSeedArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_randomize_world_seed`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_randomize_world_seed {
    /// Request that the remote module invoke the reducer `admin_randomize_world_seed` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_randomize_world_seed:admin_randomize_world_seed_then`] to run a callback after the reducer completes.
    fn admin_randomize_world_seed(&self) -> __sdk::Result<()> {
        self.admin_randomize_world_seed_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_randomize_world_seed` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_randomize_world_seed_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_randomize_world_seed for super::RemoteReducers {
    fn admin_randomize_world_seed_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdminRandomizeWorldSeedArgs {}, callback)
    }
}
