// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminDetonateArgs {
    pub radius: f32,
    pub power: f32,
}

impl From<AdminDetonateArgs> for super::Reducer {
    fn from(args: AdminDetonateArgs) -> Self {
        Self::AdminDetonate {
            radius: args.radius,
            power: args.power,
        }
    }
}

impl __sdk::InModule for AdminDetonateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_detonate`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_detonate {
    /// Request that the remote module invoke the reducer `admin_detonate` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_detonate:admin_detonate_then`] to run a callback after the reducer completes.
    fn admin_detonate(&self, radius: f32, power: f32) -> __sdk::Result<()> {
        self.admin_detonate_then(radius, power, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_detonate` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_detonate_then(
        &self,
        radius: f32,
        power: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_detonate for super::RemoteReducers {
    fn admin_detonate_then(
        &self,
        radius: f32,
        power: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdminDetonateArgs { radius, power }, callback)
    }
}
