// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminSpawnBuildingArgs {
    pub template: String,
    pub yaw_steps: u8,
    pub x: Option<f32>,
    pub z: Option<f32>,
}

impl From<AdminSpawnBuildingArgs> for super::Reducer {
    fn from(args: AdminSpawnBuildingArgs) -> Self {
        Self::AdminSpawnBuilding {
            template: args.template,
            yaw_steps: args.yaw_steps,
            x: args.x,
            z: args.z,
        }
    }
}

impl __sdk::InModule for AdminSpawnBuildingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_spawn_building`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_spawn_building {
    /// Request that the remote module invoke the reducer `admin_spawn_building` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_spawn_building:admin_spawn_building_then`] to run a callback after the reducer completes.
    fn admin_spawn_building(
        &self,
        template: String,
        yaw_steps: u8,
        x: Option<f32>,
        z: Option<f32>,
    ) -> __sdk::Result<()> {
        self.admin_spawn_building_then(template, yaw_steps, x, z, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_spawn_building` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_spawn_building_then(
        &self,
        template: String,
        yaw_steps: u8,
        x: Option<f32>,
        z: Option<f32>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_spawn_building for super::RemoteReducers {
    fn admin_spawn_building_then(
        &self,
        template: String,
        yaw_steps: u8,
        x: Option<f32>,
        z: Option<f32>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminSpawnBuildingArgs {
                template,
                yaw_steps,
                x,
                z,
            },
            callback,
        )
    }
}
