// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminSetWorldSeedArgs {
    pub seed: u32,
}

impl From<AdminSetWorldSeedArgs> for super::Reducer {
    fn from(args: AdminSetWorldSeedArgs) -> Self {
        Self::AdminSetWorldSeed { seed: args.seed }
    }
}

impl __sdk::InModule for AdminSetWorldSeedArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_set_world_seed`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_set_world_seed {
    /// Request that the remote module invoke the reducer `admin_set_world_seed` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_set_world_seed:admin_set_world_seed_then`] to run a callback after the reducer completes.
    fn admin_set_world_seed(&self, seed: u32) -> __sdk::Result<()> {
        self.admin_set_world_seed_then(seed, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_set_world_seed` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_set_world_seed_then(
        &self,
        seed: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_set_world_seed for super::RemoteReducers {
    fn admin_set_world_seed_then(
        &self,
        seed: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdminSetWorldSeedArgs { seed }, callback)
    }
}
