// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::npc_action_type::NpcAction;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AssignNpcTaskArgs {
    pub npc_id: u64,
    pub action: NpcAction,
    pub task_entity_id: Option<u64>,
    pub target_x: Option<f32>,
    pub target_y: Option<f32>,
    pub target_z: Option<f32>,
}

impl From<AssignNpcTaskArgs> for super::Reducer {
    fn from(args: AssignNpcTaskArgs) -> Self {
        Self::AssignNpcTask {
            npc_id: args.npc_id,
            action: args.action,
            task_entity_id: args.task_entity_id,
            target_x: args.target_x,
            target_y: args.target_y,
            target_z: args.target_z,
        }
    }
}

impl __sdk::InModule for AssignNpcTaskArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `assign_npc_task`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait assign_npc_task {
    /// Request that the remote module invoke the reducer `assign_npc_task` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`assign_npc_task:assign_npc_task_then`] to run a callback after the reducer completes.
    fn assign_npc_task(
        &self,
        npc_id: u64,
        action: NpcAction,
        task_entity_id: Option<u64>,
        target_x: Option<f32>,
        target_y: Option<f32>,
        target_z: Option<f32>,
    ) -> __sdk::Result<()> {
        self.assign_npc_task_then(
            npc_id,
            action,
            task_entity_id,
            target_x,
            target_y,
            target_z,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `assign_npc_task` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn assign_npc_task_then(
        &self,
        npc_id: u64,
        action: NpcAction,
        task_entity_id: Option<u64>,
        target_x: Option<f32>,
        target_y: Option<f32>,
        target_z: Option<f32>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl assign_npc_task for super::RemoteReducers {
    fn assign_npc_task_then(
        &self,
        npc_id: u64,
        action: NpcAction,
        task_entity_id: Option<u64>,
        target_x: Option<f32>,
        target_y: Option<f32>,
        target_z: Option<f32>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AssignNpcTaskArgs {
                npc_id,
                action,
                task_entity_id,
                target_x,
                target_y,
                target_z,
            },
            callback,
        )
    }
}
