// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::magic_spell_type_type::MagicSpellType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CastHighTierMagicArgs {
    pub spell_type: MagicSpellType,
    pub target_x: f32,
    pub target_y: f32,
    pub target_z: f32,
}

impl From<CastHighTierMagicArgs> for super::Reducer {
    fn from(args: CastHighTierMagicArgs) -> Self {
        Self::CastHighTierMagic {
            spell_type: args.spell_type,
            target_x: args.target_x,
            target_y: args.target_y,
            target_z: args.target_z,
        }
    }
}

impl __sdk::InModule for CastHighTierMagicArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cast_high_tier_magic`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cast_high_tier_magic {
    /// Request that the remote module invoke the reducer `cast_high_tier_magic` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`cast_high_tier_magic:cast_high_tier_magic_then`] to run a callback after the reducer completes.
    fn cast_high_tier_magic(
        &self,
        spell_type: MagicSpellType,
        target_x: f32,
        target_y: f32,
        target_z: f32,
    ) -> __sdk::Result<()> {
        self.cast_high_tier_magic_then(spell_type, target_x, target_y, target_z, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `cast_high_tier_magic` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cast_high_tier_magic_then(
        &self,
        spell_type: MagicSpellType,
        target_x: f32,
        target_y: f32,
        target_z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl cast_high_tier_magic for super::RemoteReducers {
    fn cast_high_tier_magic_then(
        &self,
        spell_type: MagicSpellType,
        target_x: f32,
        target_y: f32,
        target_z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CastHighTierMagicArgs {
                spell_type,
                target_x,
                target_y,
                target_z,
            },
            callback,
        )
    }
}
