// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::pet_stance_type::PetStance;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ChangePetStanceArgs {
    pub pet_entity_id: u64,
    pub new_stance: PetStance,
}

impl From<ChangePetStanceArgs> for super::Reducer {
    fn from(args: ChangePetStanceArgs) -> Self {
        Self::ChangePetStance {
            pet_entity_id: args.pet_entity_id,
            new_stance: args.new_stance,
        }
    }
}

impl __sdk::InModule for ChangePetStanceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `change_pet_stance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait change_pet_stance {
    /// Request that the remote module invoke the reducer `change_pet_stance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`change_pet_stance:change_pet_stance_then`] to run a callback after the reducer completes.
    fn change_pet_stance(&self, pet_entity_id: u64, new_stance: PetStance) -> __sdk::Result<()> {
        self.change_pet_stance_then(pet_entity_id, new_stance, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `change_pet_stance` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn change_pet_stance_then(
        &self,
        pet_entity_id: u64,
        new_stance: PetStance,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl change_pet_stance for super::RemoteReducers {
    fn change_pet_stance_then(
        &self,
        pet_entity_id: u64,
        new_stance: PetStance,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ChangePetStanceArgs {
                pet_entity_id,
                new_stance,
            },
            callback,
        )
    }
}
