// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ContributeConstructionArgs {
    pub structure_id: u64,
}

impl From<ContributeConstructionArgs> for super::Reducer {
    fn from(args: ContributeConstructionArgs) -> Self {
        Self::ContributeConstruction {
            structure_id: args.structure_id,
        }
    }
}

impl __sdk::InModule for ContributeConstructionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `contribute_construction`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait contribute_construction {
    /// Request that the remote module invoke the reducer `contribute_construction` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`contribute_construction:contribute_construction_then`] to run a callback after the reducer completes.
    fn contribute_construction(&self, structure_id: u64) -> __sdk::Result<()> {
        self.contribute_construction_then(structure_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `contribute_construction` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn contribute_construction_then(
        &self,
        structure_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl contribute_construction for super::RemoteReducers {
    fn contribute_construction_then(
        &self,
        structure_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ContributeConstructionArgs { structure_id }, callback)
    }
}
