// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::door_state_type::DoorState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `door_state`.
///
/// Obtain a handle from the [`DoorStateTableAccess::door_state`] method on [`super::RemoteTables`],
/// like `ctx.db.door_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.door_state().on_insert(...)`.
pub struct DoorStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<DoorState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `door_state`.
pub struct DoorStateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for DoorStateTableAccessor {
    type Row = DoorState;
    type Handle<'db> = DoorStateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.door_state()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `door_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DoorStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DoorStateTableHandle`], which mediates access to the table `door_state`.
    fn door_state(&self) -> DoorStateTableHandle<'_>;
}

impl DoorStateTableAccess for super::RemoteTables {
    fn door_state(&self) -> DoorStateTableHandle<'_> {
        DoorStateTableHandle {
            imp: self.imp.get_table::<DoorState>("door_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DoorStateInsertCallbackId(__sdk::CallbackId);
pub struct DoorStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for DoorStateTableHandle<'ctx> {
    type Row = DoorState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DoorState> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for DoorStateTableHandle<'ctx> {
    type Row = DoorState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DoorState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DoorStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DoorStateInsertCallbackId {
        DoorStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DoorStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DoorStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DoorStateDeleteCallbackId {
        DoorStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DoorStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for DoorStateTableHandle<'ctx> {
    type InsertCallbackId = DoorStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DoorStateInsertCallbackId {
        DoorStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DoorStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for DoorStateTableHandle<'ctx> {
    type DeleteCallbackId = DoorStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DoorStateDeleteCallbackId {
        DoorStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DoorStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DoorStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DoorStateTableHandle<'ctx> {
    type UpdateCallbackId = DoorStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DoorStateUpdateCallbackId {
        DoorStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DoorStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for DoorStateTableHandle<'ctx> {
    type UpdateCallbackId = DoorStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DoorStateUpdateCallbackId {
        DoorStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DoorStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `structure_id` unique index on the table `door_state`,
/// which allows point queries on the field of the same name
/// via the [`DoorStateStructureIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.door_state().structure_id().find(...)`.
pub struct DoorStateStructureIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DoorState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DoorStateTableHandle<'ctx> {
    /// Get a handle on the `structure_id` unique index on the table `door_state`.
    pub fn structure_id(&self) -> DoorStateStructureIdUnique<'ctx> {
        DoorStateStructureIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("structure_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DoorStateStructureIdUnique<'ctx> {
    /// Find the subscribed row whose `structure_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DoorState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DoorState>("door_state");
    _table.add_unique_constraint::<u64>("structure_id", |row| &row.structure_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DoorState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DoorState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DoorState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait door_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DoorState`.
    fn door_state(&self) -> __sdk::__query_builder::Table<DoorState>;
}

impl door_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn door_state(&self) -> __sdk::__query_builder::Table<DoorState> {
        __sdk::__query_builder::Table::new("door_state")
    }
}
