// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EquipWeaponArgs {
    pub slot: String,
    pub weapon_name: String,
}

impl From<EquipWeaponArgs> for super::Reducer {
    fn from(args: EquipWeaponArgs) -> Self {
        Self::EquipWeapon {
            slot: args.slot,
            weapon_name: args.weapon_name,
        }
    }
}

impl __sdk::InModule for EquipWeaponArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `equip_weapon`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait equip_weapon {
    /// Request that the remote module invoke the reducer `equip_weapon` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`equip_weapon:equip_weapon_then`] to run a callback after the reducer completes.
    fn equip_weapon(&self, slot: String, weapon_name: String) -> __sdk::Result<()> {
        self.equip_weapon_then(slot, weapon_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `equip_weapon` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn equip_weapon_then(
        &self,
        slot: String,
        weapon_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl equip_weapon for super::RemoteReducers {
    fn equip_weapon_then(
        &self,
        slot: String,
        weapon_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EquipWeaponArgs { slot, weapon_name }, callback)
    }
}
