// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EquipmentLoadout {
    pub entity_id: u64,
    pub main_hand: String,
    pub off_hand: String,
}

impl __sdk::InModule for EquipmentLoadout {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EquipmentLoadout`.
///
/// Provides typed access to columns for query building.
pub struct EquipmentLoadoutCols {
    pub entity_id: __sdk::__query_builder::Col<EquipmentLoadout, u64>,
    pub main_hand: __sdk::__query_builder::Col<EquipmentLoadout, String>,
    pub off_hand: __sdk::__query_builder::Col<EquipmentLoadout, String>,
}

impl __sdk::__query_builder::HasCols for EquipmentLoadout {
    type Cols = EquipmentLoadoutCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EquipmentLoadoutCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            main_hand: __sdk::__query_builder::Col::new(table_name, "main_hand"),
            off_hand: __sdk::__query_builder::Col::new(table_name, "off_hand"),
        }
    }
}

/// Indexed column accessor struct for the table `EquipmentLoadout`.
///
/// Provides typed access to indexed columns for query building.
pub struct EquipmentLoadoutIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<EquipmentLoadout, u64>,
}

impl __sdk::__query_builder::HasIxCols for EquipmentLoadout {
    type IxCols = EquipmentLoadoutIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EquipmentLoadoutIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EquipmentLoadout {}
