// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::faction_component_type::FactionComponent;
use super::faction_type::Faction;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `faction_component`.
///
/// Obtain a handle from the [`FactionComponentTableAccess::faction_component`] method on [`super::RemoteTables`],
/// like `ctx.db.faction_component()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.faction_component().on_insert(...)`.
pub struct FactionComponentTableHandle<'ctx> {
    imp: __sdk::TableHandle<FactionComponent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `faction_component`.
pub struct FactionComponentTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for FactionComponentTableAccessor {
    type Row = FactionComponent;
    type Handle<'db> = FactionComponentTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.faction_component()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `faction_component`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FactionComponentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FactionComponentTableHandle`], which mediates access to the table `faction_component`.
    fn faction_component(&self) -> FactionComponentTableHandle<'_>;
}

impl FactionComponentTableAccess for super::RemoteTables {
    fn faction_component(&self) -> FactionComponentTableHandle<'_> {
        FactionComponentTableHandle {
            imp: self.imp.get_table::<FactionComponent>("faction_component"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FactionComponentInsertCallbackId(__sdk::CallbackId);
pub struct FactionComponentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for FactionComponentTableHandle<'ctx> {
    type Row = FactionComponent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FactionComponent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for FactionComponentTableHandle<'ctx> {
    type Row = FactionComponent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FactionComponent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FactionComponentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FactionComponentInsertCallbackId {
        FactionComponentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FactionComponentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FactionComponentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FactionComponentDeleteCallbackId {
        FactionComponentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FactionComponentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for FactionComponentTableHandle<'ctx> {
    type InsertCallbackId = FactionComponentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FactionComponentInsertCallbackId {
        FactionComponentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FactionComponentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for FactionComponentTableHandle<'ctx> {
    type DeleteCallbackId = FactionComponentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FactionComponentDeleteCallbackId {
        FactionComponentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FactionComponentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FactionComponentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FactionComponentTableHandle<'ctx> {
    type UpdateCallbackId = FactionComponentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FactionComponentUpdateCallbackId {
        FactionComponentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FactionComponentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for FactionComponentTableHandle<'ctx> {
    type UpdateCallbackId = FactionComponentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FactionComponentUpdateCallbackId {
        FactionComponentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FactionComponentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `faction_component`,
/// which allows point queries on the field of the same name
/// via the [`FactionComponentEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.faction_component().entity_id().find(...)`.
pub struct FactionComponentEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FactionComponent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FactionComponentTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `faction_component`.
    pub fn entity_id(&self) -> FactionComponentEntityIdUnique<'ctx> {
        FactionComponentEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FactionComponentEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<FactionComponent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FactionComponent>("faction_component");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FactionComponent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FactionComponent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FactionComponent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait faction_componentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FactionComponent`.
    fn faction_component(&self) -> __sdk::__query_builder::Table<FactionComponent>;
}

impl faction_componentQueryTableAccess for __sdk::QueryTableAccessor {
    fn faction_component(&self) -> __sdk::__query_builder::Table<FactionComponent> {
        __sdk::__query_builder::Table::new("faction_component")
    }
}
