// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FallHazard {
    pub hazard_id: u64,
    pub kind: String,
    pub source_node_id: u64,
    pub origin_x: f32,
    pub origin_y: f32,
    pub origin_z: f32,
    pub dir_x: f32,
    pub dir_z: f32,
    pub length: f32,
    pub radius: f32,
    pub started_at_micros: u64,
    pub impact_at_micros: u64,
    pub duration_ms: u32,
    pub scale: f32,
    pub ruin_node_type: String,
    pub ruin_health: u32,
    pub ruin_scale: f32,
    pub ruin_required_tool: String,
}

impl __sdk::InModule for FallHazard {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `FallHazard`.
///
/// Provides typed access to columns for query building.
pub struct FallHazardCols {
    pub hazard_id: __sdk::__query_builder::Col<FallHazard, u64>,
    pub kind: __sdk::__query_builder::Col<FallHazard, String>,
    pub source_node_id: __sdk::__query_builder::Col<FallHazard, u64>,
    pub origin_x: __sdk::__query_builder::Col<FallHazard, f32>,
    pub origin_y: __sdk::__query_builder::Col<FallHazard, f32>,
    pub origin_z: __sdk::__query_builder::Col<FallHazard, f32>,
    pub dir_x: __sdk::__query_builder::Col<FallHazard, f32>,
    pub dir_z: __sdk::__query_builder::Col<FallHazard, f32>,
    pub length: __sdk::__query_builder::Col<FallHazard, f32>,
    pub radius: __sdk::__query_builder::Col<FallHazard, f32>,
    pub started_at_micros: __sdk::__query_builder::Col<FallHazard, u64>,
    pub impact_at_micros: __sdk::__query_builder::Col<FallHazard, u64>,
    pub duration_ms: __sdk::__query_builder::Col<FallHazard, u32>,
    pub scale: __sdk::__query_builder::Col<FallHazard, f32>,
    pub ruin_node_type: __sdk::__query_builder::Col<FallHazard, String>,
    pub ruin_health: __sdk::__query_builder::Col<FallHazard, u32>,
    pub ruin_scale: __sdk::__query_builder::Col<FallHazard, f32>,
    pub ruin_required_tool: __sdk::__query_builder::Col<FallHazard, String>,
}

impl __sdk::__query_builder::HasCols for FallHazard {
    type Cols = FallHazardCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FallHazardCols {
            hazard_id: __sdk::__query_builder::Col::new(table_name, "hazard_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            source_node_id: __sdk::__query_builder::Col::new(table_name, "source_node_id"),
            origin_x: __sdk::__query_builder::Col::new(table_name, "origin_x"),
            origin_y: __sdk::__query_builder::Col::new(table_name, "origin_y"),
            origin_z: __sdk::__query_builder::Col::new(table_name, "origin_z"),
            dir_x: __sdk::__query_builder::Col::new(table_name, "dir_x"),
            dir_z: __sdk::__query_builder::Col::new(table_name, "dir_z"),
            length: __sdk::__query_builder::Col::new(table_name, "length"),
            radius: __sdk::__query_builder::Col::new(table_name, "radius"),
            started_at_micros: __sdk::__query_builder::Col::new(table_name, "started_at_micros"),
            impact_at_micros: __sdk::__query_builder::Col::new(table_name, "impact_at_micros"),
            duration_ms: __sdk::__query_builder::Col::new(table_name, "duration_ms"),
            scale: __sdk::__query_builder::Col::new(table_name, "scale"),
            ruin_node_type: __sdk::__query_builder::Col::new(table_name, "ruin_node_type"),
            ruin_health: __sdk::__query_builder::Col::new(table_name, "ruin_health"),
            ruin_scale: __sdk::__query_builder::Col::new(table_name, "ruin_scale"),
            ruin_required_tool: __sdk::__query_builder::Col::new(table_name, "ruin_required_tool"),
        }
    }
}

/// Indexed column accessor struct for the table `FallHazard`.
///
/// Provides typed access to indexed columns for query building.
pub struct FallHazardIxCols {
    pub hazard_id: __sdk::__query_builder::IxCol<FallHazard, u64>,
}

impl __sdk::__query_builder::HasIxCols for FallHazard {
    type IxCols = FallHazardIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FallHazardIxCols {
            hazard_id: __sdk::__query_builder::IxCol::new(table_name, "hazard_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for FallHazard {}
