// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::siege_weapon_type_type::SiegeWeaponType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FireSiegeWeaponArgs {
    pub siege_type: SiegeWeaponType,
    pub origin_x: f32,
    pub origin_y: f32,
    pub origin_z: f32,
    pub dir_x: f32,
    pub dir_y: f32,
    pub dir_z: f32,
}

impl From<FireSiegeWeaponArgs> for super::Reducer {
    fn from(args: FireSiegeWeaponArgs) -> Self {
        Self::FireSiegeWeapon {
            siege_type: args.siege_type,
            origin_x: args.origin_x,
            origin_y: args.origin_y,
            origin_z: args.origin_z,
            dir_x: args.dir_x,
            dir_y: args.dir_y,
            dir_z: args.dir_z,
        }
    }
}

impl __sdk::InModule for FireSiegeWeaponArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `fire_siege_weapon`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait fire_siege_weapon {
    /// Request that the remote module invoke the reducer `fire_siege_weapon` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`fire_siege_weapon:fire_siege_weapon_then`] to run a callback after the reducer completes.
    fn fire_siege_weapon(
        &self,
        siege_type: SiegeWeaponType,
        origin_x: f32,
        origin_y: f32,
        origin_z: f32,
        dir_x: f32,
        dir_y: f32,
        dir_z: f32,
    ) -> __sdk::Result<()> {
        self.fire_siege_weapon_then(
            siege_type,
            origin_x,
            origin_y,
            origin_z,
            dir_x,
            dir_y,
            dir_z,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `fire_siege_weapon` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn fire_siege_weapon_then(
        &self,
        siege_type: SiegeWeaponType,
        origin_x: f32,
        origin_y: f32,
        origin_z: f32,
        dir_x: f32,
        dir_y: f32,
        dir_z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl fire_siege_weapon for super::RemoteReducers {
    fn fire_siege_weapon_then(
        &self,
        siege_type: SiegeWeaponType,
        origin_x: f32,
        origin_y: f32,
        origin_z: f32,
        dir_x: f32,
        dir_y: f32,
        dir_z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            FireSiegeWeaponArgs {
                siege_type,
                origin_x,
                origin_y,
                origin_z,
                dir_x,
                dir_y,
                dir_z,
            },
            callback,
        )
    }
}
