// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::global_state_type::GlobalState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `global_state`.
///
/// Obtain a handle from the [`GlobalStateTableAccess::global_state`] method on [`super::RemoteTables`],
/// like `ctx.db.global_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.global_state().on_insert(...)`.
pub struct GlobalStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<GlobalState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `global_state`.
pub struct GlobalStateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GlobalStateTableAccessor {
    type Row = GlobalState;
    type Handle<'db> = GlobalStateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.global_state()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `global_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GlobalStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GlobalStateTableHandle`], which mediates access to the table `global_state`.
    fn global_state(&self) -> GlobalStateTableHandle<'_>;
}

impl GlobalStateTableAccess for super::RemoteTables {
    fn global_state(&self) -> GlobalStateTableHandle<'_> {
        GlobalStateTableHandle {
            imp: self.imp.get_table::<GlobalState>("global_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GlobalStateInsertCallbackId(__sdk::CallbackId);
pub struct GlobalStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GlobalStateTableHandle<'ctx> {
    type Row = GlobalState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GlobalState> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GlobalStateTableHandle<'ctx> {
    type Row = GlobalState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GlobalState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GlobalStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GlobalStateInsertCallbackId {
        GlobalStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GlobalStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GlobalStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GlobalStateDeleteCallbackId {
        GlobalStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GlobalStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GlobalStateTableHandle<'ctx> {
    type InsertCallbackId = GlobalStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GlobalStateInsertCallbackId {
        GlobalStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GlobalStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GlobalStateTableHandle<'ctx> {
    type DeleteCallbackId = GlobalStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GlobalStateDeleteCallbackId {
        GlobalStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GlobalStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GlobalStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GlobalStateTableHandle<'ctx> {
    type UpdateCallbackId = GlobalStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GlobalStateUpdateCallbackId {
        GlobalStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GlobalStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GlobalStateTableHandle<'ctx> {
    type UpdateCallbackId = GlobalStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GlobalStateUpdateCallbackId {
        GlobalStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GlobalStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `global_state`,
/// which allows point queries on the field of the same name
/// via the [`GlobalStateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.global_state().id().find(...)`.
pub struct GlobalStateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GlobalState, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GlobalStateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `global_state`.
    pub fn id(&self) -> GlobalStateIdUnique<'ctx> {
        GlobalStateIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GlobalStateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<GlobalState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GlobalState>("global_state");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GlobalState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GlobalState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GlobalState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait global_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GlobalState`.
    fn global_state(&self) -> __sdk::__query_builder::Table<GlobalState>;
}

impl global_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn global_state(&self) -> __sdk::__query_builder::Table<GlobalState> {
        __sdk::__query_builder::Table::new("global_state")
    }
}
