// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HazardImpactTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub hazard_id: u64,
}

impl __sdk::InModule for HazardImpactTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HazardImpactTimer`.
///
/// Provides typed access to columns for query building.
pub struct HazardImpactTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<HazardImpactTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<HazardImpactTimer, __sdk::ScheduleAt>,
    pub hazard_id: __sdk::__query_builder::Col<HazardImpactTimer, u64>,
}

impl __sdk::__query_builder::HasCols for HazardImpactTimer {
    type Cols = HazardImpactTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HazardImpactTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            hazard_id: __sdk::__query_builder::Col::new(table_name, "hazard_id"),
        }
    }
}

/// Indexed column accessor struct for the table `HazardImpactTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct HazardImpactTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<HazardImpactTimer, u64>,
}

impl __sdk::__query_builder::HasIxCols for HazardImpactTimer {
    type IxCols = HazardImpactTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HazardImpactTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for HazardImpactTimer {}
