// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::hitbox_history_type::HitboxHistory;
use super::snapshot_type::Snapshot;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `hitbox_history`.
///
/// Obtain a handle from the [`HitboxHistoryTableAccess::hitbox_history`] method on [`super::RemoteTables`],
/// like `ctx.db.hitbox_history()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hitbox_history().on_insert(...)`.
pub struct HitboxHistoryTableHandle<'ctx> {
    imp: __sdk::TableHandle<HitboxHistory>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `hitbox_history`.
pub struct HitboxHistoryTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for HitboxHistoryTableAccessor {
    type Row = HitboxHistory;
    type Handle<'db> = HitboxHistoryTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.hitbox_history()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `hitbox_history`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HitboxHistoryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HitboxHistoryTableHandle`], which mediates access to the table `hitbox_history`.
    fn hitbox_history(&self) -> HitboxHistoryTableHandle<'_>;
}

impl HitboxHistoryTableAccess for super::RemoteTables {
    fn hitbox_history(&self) -> HitboxHistoryTableHandle<'_> {
        HitboxHistoryTableHandle {
            imp: self.imp.get_table::<HitboxHistory>("hitbox_history"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HitboxHistoryInsertCallbackId(__sdk::CallbackId);
pub struct HitboxHistoryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for HitboxHistoryTableHandle<'ctx> {
    type Row = HitboxHistory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HitboxHistory> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for HitboxHistoryTableHandle<'ctx> {
    type Row = HitboxHistory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HitboxHistory> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HitboxHistoryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HitboxHistoryInsertCallbackId {
        HitboxHistoryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HitboxHistoryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HitboxHistoryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HitboxHistoryDeleteCallbackId {
        HitboxHistoryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HitboxHistoryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for HitboxHistoryTableHandle<'ctx> {
    type InsertCallbackId = HitboxHistoryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HitboxHistoryInsertCallbackId {
        HitboxHistoryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HitboxHistoryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for HitboxHistoryTableHandle<'ctx> {
    type DeleteCallbackId = HitboxHistoryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HitboxHistoryDeleteCallbackId {
        HitboxHistoryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HitboxHistoryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct HitboxHistoryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for HitboxHistoryTableHandle<'ctx> {
    type UpdateCallbackId = HitboxHistoryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HitboxHistoryUpdateCallbackId {
        HitboxHistoryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HitboxHistoryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for HitboxHistoryTableHandle<'ctx> {
    type UpdateCallbackId = HitboxHistoryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HitboxHistoryUpdateCallbackId {
        HitboxHistoryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HitboxHistoryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `hitbox_history`,
/// which allows point queries on the field of the same name
/// via the [`HitboxHistoryEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hitbox_history().entity_id().find(...)`.
pub struct HitboxHistoryEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<HitboxHistory, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> HitboxHistoryTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `hitbox_history`.
    pub fn entity_id(&self) -> HitboxHistoryEntityIdUnique<'ctx> {
        HitboxHistoryEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> HitboxHistoryEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<HitboxHistory> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<HitboxHistory>("hitbox_history");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<HitboxHistory>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<HitboxHistory>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `HitboxHistory`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait hitbox_historyQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `HitboxHistory`.
    fn hitbox_history(&self) -> __sdk::__query_builder::Table<HitboxHistory>;
}

impl hitbox_historyQueryTableAccess for __sdk::QueryTableAccessor {
    fn hitbox_history(&self) -> __sdk::__query_builder::Table<HitboxHistory> {
        __sdk::__query_builder::Table::new("hitbox_history")
    }
}
