// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::material_properties_type::MaterialProperties;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `material_properties`.
///
/// Obtain a handle from the [`MaterialPropertiesTableAccess::material_properties`] method on [`super::RemoteTables`],
/// like `ctx.db.material_properties()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.material_properties().on_insert(...)`.
pub struct MaterialPropertiesTableHandle<'ctx> {
    imp: __sdk::TableHandle<MaterialProperties>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `material_properties`.
pub struct MaterialPropertiesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MaterialPropertiesTableAccessor {
    type Row = MaterialProperties;
    type Handle<'db> = MaterialPropertiesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.material_properties()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `material_properties`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MaterialPropertiesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MaterialPropertiesTableHandle`], which mediates access to the table `material_properties`.
    fn material_properties(&self) -> MaterialPropertiesTableHandle<'_>;
}

impl MaterialPropertiesTableAccess for super::RemoteTables {
    fn material_properties(&self) -> MaterialPropertiesTableHandle<'_> {
        MaterialPropertiesTableHandle {
            imp: self
                .imp
                .get_table::<MaterialProperties>("material_properties"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MaterialPropertiesInsertCallbackId(__sdk::CallbackId);
pub struct MaterialPropertiesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MaterialPropertiesTableHandle<'ctx> {
    type Row = MaterialProperties;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MaterialProperties> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MaterialPropertiesTableHandle<'ctx> {
    type Row = MaterialProperties;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MaterialProperties> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MaterialPropertiesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MaterialPropertiesInsertCallbackId {
        MaterialPropertiesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MaterialPropertiesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MaterialPropertiesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MaterialPropertiesDeleteCallbackId {
        MaterialPropertiesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MaterialPropertiesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MaterialPropertiesTableHandle<'ctx> {
    type InsertCallbackId = MaterialPropertiesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MaterialPropertiesInsertCallbackId {
        MaterialPropertiesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MaterialPropertiesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MaterialPropertiesTableHandle<'ctx> {
    type DeleteCallbackId = MaterialPropertiesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MaterialPropertiesDeleteCallbackId {
        MaterialPropertiesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MaterialPropertiesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MaterialPropertiesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MaterialPropertiesTableHandle<'ctx> {
    type UpdateCallbackId = MaterialPropertiesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MaterialPropertiesUpdateCallbackId {
        MaterialPropertiesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MaterialPropertiesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MaterialPropertiesTableHandle<'ctx> {
    type UpdateCallbackId = MaterialPropertiesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MaterialPropertiesUpdateCallbackId {
        MaterialPropertiesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MaterialPropertiesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `material_name` unique index on the table `material_properties`,
/// which allows point queries on the field of the same name
/// via the [`MaterialPropertiesMaterialNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.material_properties().material_name().find(...)`.
pub struct MaterialPropertiesMaterialNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MaterialProperties, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MaterialPropertiesTableHandle<'ctx> {
    /// Get a handle on the `material_name` unique index on the table `material_properties`.
    pub fn material_name(&self) -> MaterialPropertiesMaterialNameUnique<'ctx> {
        MaterialPropertiesMaterialNameUnique {
            imp: self.imp.get_unique_constraint::<String>("material_name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MaterialPropertiesMaterialNameUnique<'ctx> {
    /// Find the subscribed row whose `material_name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<MaterialProperties> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MaterialProperties>("material_properties");
    _table.add_unique_constraint::<String>("material_name", |row| &row.material_name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MaterialProperties>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MaterialProperties>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MaterialProperties`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait material_propertiesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MaterialProperties`.
    fn material_properties(&self) -> __sdk::__query_builder::Table<MaterialProperties>;
}

impl material_propertiesQueryTableAccess for __sdk::QueryTableAccessor {
    fn material_properties(&self) -> __sdk::__query_builder::Table<MaterialProperties> {
        __sdk::__query_builder::Table::new("material_properties")
    }
}
