// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MaterialProperties {
    pub material_name: String,
    pub max_support: f32,
    pub min_support: f32,
    pub horizontal_loss_coeff: f32,
    pub vertical_loss_coeff: f32,
}

impl __sdk::InModule for MaterialProperties {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MaterialProperties`.
///
/// Provides typed access to columns for query building.
pub struct MaterialPropertiesCols {
    pub material_name: __sdk::__query_builder::Col<MaterialProperties, String>,
    pub max_support: __sdk::__query_builder::Col<MaterialProperties, f32>,
    pub min_support: __sdk::__query_builder::Col<MaterialProperties, f32>,
    pub horizontal_loss_coeff: __sdk::__query_builder::Col<MaterialProperties, f32>,
    pub vertical_loss_coeff: __sdk::__query_builder::Col<MaterialProperties, f32>,
}

impl __sdk::__query_builder::HasCols for MaterialProperties {
    type Cols = MaterialPropertiesCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MaterialPropertiesCols {
            material_name: __sdk::__query_builder::Col::new(table_name, "material_name"),
            max_support: __sdk::__query_builder::Col::new(table_name, "max_support"),
            min_support: __sdk::__query_builder::Col::new(table_name, "min_support"),
            horizontal_loss_coeff: __sdk::__query_builder::Col::new(
                table_name,
                "horizontal_loss_coeff",
            ),
            vertical_loss_coeff: __sdk::__query_builder::Col::new(
                table_name,
                "vertical_loss_coeff",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `MaterialProperties`.
///
/// Provides typed access to indexed columns for query building.
pub struct MaterialPropertiesIxCols {
    pub material_name: __sdk::__query_builder::IxCol<MaterialProperties, String>,
}

impl __sdk::__query_builder::HasIxCols for MaterialProperties {
    type IxCols = MaterialPropertiesIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MaterialPropertiesIxCols {
            material_name: __sdk::__query_builder::IxCol::new(table_name, "material_name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MaterialProperties {}
