// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod ai_state_type;
pub mod ai_type_type;
pub mod brain_state_type;
pub mod camera_mode_type_type;
pub mod change_pet_stance_reducer;
pub mod combat_event_table;
pub mod combat_event_type;
pub mod command_peasant_reducer;
pub mod consume_item_reducer;
pub mod contribute_construction_reducer;
pub mod craft_item_reducer;
pub mod destroy_structure_reducer;
pub mod faction_component_table;
pub mod faction_component_type;
pub mod faction_type;
pub mod fire_bow_reducer;
pub mod fire_weapon_reducer;
pub mod global_state_table;
pub mod global_state_type;
pub mod harvestable_corpse_table;
pub mod harvestable_corpse_type;
pub mod health_table;
pub mod health_type;
pub mod high_frequency_timer_type;
pub mod hitbox_history_table;
pub mod hitbox_history_type;
pub mod interact_node_reducer;
pub mod inventory_slot_type;
pub mod inventory_table;
pub mod inventory_type;
pub mod issue_waypoint_reducer;
pub mod low_frequency_timer_type;
pub mod nav_event_table;
pub mod nav_event_type;
pub mod npc_brain_table;
pub mod npc_brain_type;
pub mod peasant_table;
pub mod peasant_type;
pub mod pet_component_table;
pub mod pet_component_type;
pub mod pet_stance_type;
pub mod place_structure_reducer;
pub mod player_perspective_table;
pub mod player_perspective_type;
pub mod player_session_table;
pub mod player_session_type;
pub mod player_table;
pub mod player_type;
pub mod position_type;
pub mod process_movement_reducer;
pub mod repair_structure_reducer;
pub mod resource_node_table;
pub mod resource_node_type;
pub mod respawn_bush_timer_type;
pub mod set_camera_mode_reducer;
pub mod set_interior_culling_reducer;
pub mod snapshot_type;
pub mod spawn_peasant_reducer;
pub mod structure_table;
pub mod structure_type;
pub mod swing_tool_reducer;
pub mod transform_table;
pub mod transform_type;
pub mod waypoint_table;
pub mod waypoint_type;

pub use ai_state_type::AiState;
pub use ai_type_type::AiType;
pub use brain_state_type::BrainState;
pub use camera_mode_type_type::CameraModeType;
pub use change_pet_stance_reducer::change_pet_stance;
pub use combat_event_table::*;
pub use combat_event_type::CombatEvent;
pub use command_peasant_reducer::command_peasant;
pub use consume_item_reducer::consume_item;
pub use contribute_construction_reducer::contribute_construction;
pub use craft_item_reducer::craft_item;
pub use destroy_structure_reducer::destroy_structure;
pub use faction_component_table::*;
pub use faction_component_type::FactionComponent;
pub use faction_type::Faction;
pub use fire_bow_reducer::fire_bow;
pub use fire_weapon_reducer::fire_weapon;
pub use global_state_table::*;
pub use global_state_type::GlobalState;
pub use harvestable_corpse_table::*;
pub use harvestable_corpse_type::HarvestableCorpse;
pub use health_table::*;
pub use health_type::Health;
pub use high_frequency_timer_type::HighFrequencyTimer;
pub use hitbox_history_table::*;
pub use hitbox_history_type::HitboxHistory;
pub use interact_node_reducer::interact_node;
pub use inventory_slot_type::InventorySlot;
pub use inventory_table::*;
pub use inventory_type::Inventory;
pub use issue_waypoint_reducer::issue_waypoint;
pub use low_frequency_timer_type::LowFrequencyTimer;
pub use nav_event_table::*;
pub use nav_event_type::NavEvent;
pub use npc_brain_table::*;
pub use npc_brain_type::NpcBrain;
pub use peasant_table::*;
pub use peasant_type::Peasant;
pub use pet_component_table::*;
pub use pet_component_type::PetComponent;
pub use pet_stance_type::PetStance;
pub use place_structure_reducer::place_structure;
pub use player_perspective_table::*;
pub use player_perspective_type::PlayerPerspective;
pub use player_session_table::*;
pub use player_session_type::PlayerSession;
pub use player_table::*;
pub use player_type::Player;
pub use position_type::Position;
pub use process_movement_reducer::process_movement;
pub use repair_structure_reducer::repair_structure;
pub use resource_node_table::*;
pub use resource_node_type::ResourceNode;
pub use respawn_bush_timer_type::RespawnBushTimer;
pub use set_camera_mode_reducer::set_camera_mode;
pub use set_interior_culling_reducer::set_interior_culling;
pub use snapshot_type::Snapshot;
pub use spawn_peasant_reducer::spawn_peasant;
pub use structure_table::*;
pub use structure_type::Structure;
pub use swing_tool_reducer::swing_tool;
pub use transform_table::*;
pub use transform_type::Transform;
pub use waypoint_table::*;
pub use waypoint_type::Waypoint;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    ChangePetStance {
        pet_entity_id: u64,
        new_stance: PetStance,
    },
    CommandPeasant {
        peasant_entity_id: u64,
        command_type: String,
        target_x: f32,
        target_y: f32,
        target_z: f32,
        target_id: u64,
    },
    ConsumeItem {
        item_name: String,
    },
    ContributeConstruction {
        structure_id: u64,
    },
    CraftItem {
        item_name: String,
    },
    DestroyStructure {
        target_structure_id: u64,
    },
    FireBow {
        client_tick: u64,
        origin_x: f32,
        origin_y: f32,
        origin_z: f32,
        dir_x: f32,
        dir_y: f32,
        dir_z: f32,
    },
    FireWeapon {
        client_tick: u64,
        origin_x: f32,
        origin_y: f32,
        origin_z: f32,
        dir_x: f32,
        dir_y: f32,
        dir_z: f32,
    },
    InteractNode {
        node_id: u64,
    },
    IssueWaypoint {
        x: f32,
        y: f32,
        z: f32,
        order_type: String,
    },
    PlaceStructure {
        parent_id: Option<u64>,
        piece_type: String,
        x: f32,
        y: f32,
        z: f32,
        rot_x: f32,
        rot_y: f32,
        rot_z: f32,
        rot_w: f32,
    },
    ProcessMovement {
        tick_id: u64,
        delta_x: f32,
        delta_y: f32,
        delta_z: f32,
    },
    RepairStructure {
        structure_id: u64,
    },
    SetCameraMode {
        mode: CameraModeType,
    },
    SetInteriorCulling {
        in_interior: bool,
    },
    SpawnPeasant,
    SwingTool {
        px: f32,
        py: f32,
        pz: f32,
        dx: f32,
        dy: f32,
        dz: f32,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::ChangePetStance { .. } => "change_pet_stance",
            Reducer::CommandPeasant { .. } => "command_peasant",
            Reducer::ConsumeItem { .. } => "consume_item",
            Reducer::ContributeConstruction { .. } => "contribute_construction",
            Reducer::CraftItem { .. } => "craft_item",
            Reducer::DestroyStructure { .. } => "destroy_structure",
            Reducer::FireBow { .. } => "fire_bow",
            Reducer::FireWeapon { .. } => "fire_weapon",
            Reducer::InteractNode { .. } => "interact_node",
            Reducer::IssueWaypoint { .. } => "issue_waypoint",
            Reducer::PlaceStructure { .. } => "place_structure",
            Reducer::ProcessMovement { .. } => "process_movement",
            Reducer::RepairStructure { .. } => "repair_structure",
            Reducer::SetCameraMode { .. } => "set_camera_mode",
            Reducer::SetInteriorCulling { .. } => "set_interior_culling",
            Reducer::SpawnPeasant => "spawn_peasant",
            Reducer::SwingTool { .. } => "swing_tool",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::ChangePetStance {
                pet_entity_id,
                new_stance,
            } => __sats::bsatn::to_vec(&change_pet_stance_reducer::ChangePetStanceArgs {
                pet_entity_id: pet_entity_id.clone(),
                new_stance: new_stance.clone(),
            }),
            Reducer::CommandPeasant {
                peasant_entity_id,
                command_type,
                target_x,
                target_y,
                target_z,
                target_id,
            } => __sats::bsatn::to_vec(&command_peasant_reducer::CommandPeasantArgs {
                peasant_entity_id: peasant_entity_id.clone(),
                command_type: command_type.clone(),
                target_x: target_x.clone(),
                target_y: target_y.clone(),
                target_z: target_z.clone(),
                target_id: target_id.clone(),
            }),
            Reducer::ConsumeItem { item_name } => {
                __sats::bsatn::to_vec(&consume_item_reducer::ConsumeItemArgs {
                    item_name: item_name.clone(),
                })
            }
            Reducer::ContributeConstruction { structure_id } => __sats::bsatn::to_vec(
                &contribute_construction_reducer::ContributeConstructionArgs {
                    structure_id: structure_id.clone(),
                },
            ),
            Reducer::CraftItem { item_name } => {
                __sats::bsatn::to_vec(&craft_item_reducer::CraftItemArgs {
                    item_name: item_name.clone(),
                })
            }
            Reducer::DestroyStructure {
                target_structure_id,
            } => __sats::bsatn::to_vec(&destroy_structure_reducer::DestroyStructureArgs {
                target_structure_id: target_structure_id.clone(),
            }),
            Reducer::FireBow {
                client_tick,
                origin_x,
                origin_y,
                origin_z,
                dir_x,
                dir_y,
                dir_z,
            } => __sats::bsatn::to_vec(&fire_bow_reducer::FireBowArgs {
                client_tick: client_tick.clone(),
                origin_x: origin_x.clone(),
                origin_y: origin_y.clone(),
                origin_z: origin_z.clone(),
                dir_x: dir_x.clone(),
                dir_y: dir_y.clone(),
                dir_z: dir_z.clone(),
            }),
            Reducer::FireWeapon {
                client_tick,
                origin_x,
                origin_y,
                origin_z,
                dir_x,
                dir_y,
                dir_z,
            } => __sats::bsatn::to_vec(&fire_weapon_reducer::FireWeaponArgs {
                client_tick: client_tick.clone(),
                origin_x: origin_x.clone(),
                origin_y: origin_y.clone(),
                origin_z: origin_z.clone(),
                dir_x: dir_x.clone(),
                dir_y: dir_y.clone(),
                dir_z: dir_z.clone(),
            }),
            Reducer::InteractNode { node_id } => {
                __sats::bsatn::to_vec(&interact_node_reducer::InteractNodeArgs {
                    node_id: node_id.clone(),
                })
            }
            Reducer::IssueWaypoint {
                x,
                y,
                z,
                order_type,
            } => __sats::bsatn::to_vec(&issue_waypoint_reducer::IssueWaypointArgs {
                x: x.clone(),
                y: y.clone(),
                z: z.clone(),
                order_type: order_type.clone(),
            }),
            Reducer::PlaceStructure {
                parent_id,
                piece_type,
                x,
                y,
                z,
                rot_x,
                rot_y,
                rot_z,
                rot_w,
            } => __sats::bsatn::to_vec(&place_structure_reducer::PlaceStructureArgs {
                parent_id: parent_id.clone(),
                piece_type: piece_type.clone(),
                x: x.clone(),
                y: y.clone(),
                z: z.clone(),
                rot_x: rot_x.clone(),
                rot_y: rot_y.clone(),
                rot_z: rot_z.clone(),
                rot_w: rot_w.clone(),
            }),
            Reducer::ProcessMovement {
                tick_id,
                delta_x,
                delta_y,
                delta_z,
            } => __sats::bsatn::to_vec(&process_movement_reducer::ProcessMovementArgs {
                tick_id: tick_id.clone(),
                delta_x: delta_x.clone(),
                delta_y: delta_y.clone(),
                delta_z: delta_z.clone(),
            }),
            Reducer::RepairStructure { structure_id } => {
                __sats::bsatn::to_vec(&repair_structure_reducer::RepairStructureArgs {
                    structure_id: structure_id.clone(),
                })
            }
            Reducer::SetCameraMode { mode } => {
                __sats::bsatn::to_vec(&set_camera_mode_reducer::SetCameraModeArgs {
                    mode: mode.clone(),
                })
            }
            Reducer::SetInteriorCulling { in_interior } => {
                __sats::bsatn::to_vec(&set_interior_culling_reducer::SetInteriorCullingArgs {
                    in_interior: in_interior.clone(),
                })
            }
            Reducer::SpawnPeasant => {
                __sats::bsatn::to_vec(&spawn_peasant_reducer::SpawnPeasantArgs {})
            }
            Reducer::SwingTool {
                px,
                py,
                pz,
                dx,
                dy,
                dz,
            } => __sats::bsatn::to_vec(&swing_tool_reducer::SwingToolArgs {
                px: px.clone(),
                py: py.clone(),
                pz: pz.clone(),
                dx: dx.clone(),
                dy: dy.clone(),
                dz: dz.clone(),
            }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    combat_event: __sdk::TableUpdate<CombatEvent>,
    faction_component: __sdk::TableUpdate<FactionComponent>,
    global_state: __sdk::TableUpdate<GlobalState>,
    harvestable_corpse: __sdk::TableUpdate<HarvestableCorpse>,
    health: __sdk::TableUpdate<Health>,
    hitbox_history: __sdk::TableUpdate<HitboxHistory>,
    inventory: __sdk::TableUpdate<Inventory>,
    nav_event: __sdk::TableUpdate<NavEvent>,
    npc_brain: __sdk::TableUpdate<NpcBrain>,
    peasant: __sdk::TableUpdate<Peasant>,
    pet_component: __sdk::TableUpdate<PetComponent>,
    player: __sdk::TableUpdate<Player>,
    player_perspective: __sdk::TableUpdate<PlayerPerspective>,
    player_session: __sdk::TableUpdate<PlayerSession>,
    resource_node: __sdk::TableUpdate<ResourceNode>,
    structure: __sdk::TableUpdate<Structure>,
    transform: __sdk::TableUpdate<Transform>,
    waypoint: __sdk::TableUpdate<Waypoint>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "combat_event" => db_update
                    .combat_event
                    .append(combat_event_table::parse_table_update(table_update)?),
                "faction_component" => db_update
                    .faction_component
                    .append(faction_component_table::parse_table_update(table_update)?),
                "global_state" => db_update
                    .global_state
                    .append(global_state_table::parse_table_update(table_update)?),
                "harvestable_corpse" => db_update
                    .harvestable_corpse
                    .append(harvestable_corpse_table::parse_table_update(table_update)?),
                "health" => db_update
                    .health
                    .append(health_table::parse_table_update(table_update)?),
                "hitbox_history" => db_update
                    .hitbox_history
                    .append(hitbox_history_table::parse_table_update(table_update)?),
                "inventory" => db_update
                    .inventory
                    .append(inventory_table::parse_table_update(table_update)?),
                "nav_event" => db_update
                    .nav_event
                    .append(nav_event_table::parse_table_update(table_update)?),
                "npc_brain" => db_update
                    .npc_brain
                    .append(npc_brain_table::parse_table_update(table_update)?),
                "peasant" => db_update
                    .peasant
                    .append(peasant_table::parse_table_update(table_update)?),
                "pet_component" => db_update
                    .pet_component
                    .append(pet_component_table::parse_table_update(table_update)?),
                "player" => db_update
                    .player
                    .append(player_table::parse_table_update(table_update)?),
                "player_perspective" => db_update
                    .player_perspective
                    .append(player_perspective_table::parse_table_update(table_update)?),
                "player_session" => db_update
                    .player_session
                    .append(player_session_table::parse_table_update(table_update)?),
                "resource_node" => db_update
                    .resource_node
                    .append(resource_node_table::parse_table_update(table_update)?),
                "structure" => db_update
                    .structure
                    .append(structure_table::parse_table_update(table_update)?),
                "transform" => db_update
                    .transform
                    .append(transform_table::parse_table_update(table_update)?),
                "waypoint" => db_update
                    .waypoint
                    .append(waypoint_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.combat_event = cache
            .apply_diff_to_table::<CombatEvent>("combat_event", &self.combat_event)
            .with_updates_by_pk(|row| &row.id);
        diff.faction_component = cache
            .apply_diff_to_table::<FactionComponent>("faction_component", &self.faction_component)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.global_state = cache
            .apply_diff_to_table::<GlobalState>("global_state", &self.global_state)
            .with_updates_by_pk(|row| &row.id);
        diff.harvestable_corpse = cache
            .apply_diff_to_table::<HarvestableCorpse>(
                "harvestable_corpse",
                &self.harvestable_corpse,
            )
            .with_updates_by_pk(|row| &row.entity_id);
        diff.health = cache
            .apply_diff_to_table::<Health>("health", &self.health)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.hitbox_history = cache
            .apply_diff_to_table::<HitboxHistory>("hitbox_history", &self.hitbox_history)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.inventory = cache
            .apply_diff_to_table::<Inventory>("inventory", &self.inventory)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.nav_event = cache
            .apply_diff_to_table::<NavEvent>("nav_event", &self.nav_event)
            .with_updates_by_pk(|row| &row.id);
        diff.npc_brain = cache
            .apply_diff_to_table::<NpcBrain>("npc_brain", &self.npc_brain)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.peasant = cache
            .apply_diff_to_table::<Peasant>("peasant", &self.peasant)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.pet_component = cache
            .apply_diff_to_table::<PetComponent>("pet_component", &self.pet_component)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.player = cache
            .apply_diff_to_table::<Player>("player", &self.player)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.player_perspective = cache
            .apply_diff_to_table::<PlayerPerspective>(
                "player_perspective",
                &self.player_perspective,
            )
            .with_updates_by_pk(|row| &row.entity_id);
        diff.player_session = cache
            .apply_diff_to_table::<PlayerSession>("player_session", &self.player_session)
            .with_updates_by_pk(|row| &row.identity);
        diff.resource_node = cache
            .apply_diff_to_table::<ResourceNode>("resource_node", &self.resource_node)
            .with_updates_by_pk(|row| &row.node_id);
        diff.structure = cache
            .apply_diff_to_table::<Structure>("structure", &self.structure)
            .with_updates_by_pk(|row| &row.structure_id);
        diff.transform = cache
            .apply_diff_to_table::<Transform>("transform", &self.transform)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.waypoint = cache
            .apply_diff_to_table::<Waypoint>("waypoint", &self.waypoint)
            .with_updates_by_pk(|row| &row.waypoint_id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "combat_event" => db_update
                    .combat_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "faction_component" => db_update
                    .faction_component
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "global_state" => db_update
                    .global_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "harvestable_corpse" => db_update
                    .harvestable_corpse
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "health" => db_update
                    .health
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "hitbox_history" => db_update
                    .hitbox_history
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "inventory" => db_update
                    .inventory
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "nav_event" => db_update
                    .nav_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "npc_brain" => db_update
                    .npc_brain
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "peasant" => db_update
                    .peasant
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "pet_component" => db_update
                    .pet_component
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_perspective" => db_update
                    .player_perspective
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_session" => db_update
                    .player_session
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "resource_node" => db_update
                    .resource_node
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "structure" => db_update
                    .structure
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "transform" => db_update
                    .transform
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "waypoint" => db_update
                    .waypoint
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "combat_event" => db_update
                    .combat_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "faction_component" => db_update
                    .faction_component
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "global_state" => db_update
                    .global_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "harvestable_corpse" => db_update
                    .harvestable_corpse
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "health" => db_update
                    .health
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "hitbox_history" => db_update
                    .hitbox_history
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "inventory" => db_update
                    .inventory
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "nav_event" => db_update
                    .nav_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "npc_brain" => db_update
                    .npc_brain
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "peasant" => db_update
                    .peasant
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "pet_component" => db_update
                    .pet_component
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_perspective" => db_update
                    .player_perspective
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_session" => db_update
                    .player_session
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "resource_node" => db_update
                    .resource_node
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "structure" => db_update
                    .structure
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "transform" => db_update
                    .transform
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "waypoint" => db_update
                    .waypoint
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    combat_event: __sdk::TableAppliedDiff<'r, CombatEvent>,
    faction_component: __sdk::TableAppliedDiff<'r, FactionComponent>,
    global_state: __sdk::TableAppliedDiff<'r, GlobalState>,
    harvestable_corpse: __sdk::TableAppliedDiff<'r, HarvestableCorpse>,
    health: __sdk::TableAppliedDiff<'r, Health>,
    hitbox_history: __sdk::TableAppliedDiff<'r, HitboxHistory>,
    inventory: __sdk::TableAppliedDiff<'r, Inventory>,
    nav_event: __sdk::TableAppliedDiff<'r, NavEvent>,
    npc_brain: __sdk::TableAppliedDiff<'r, NpcBrain>,
    peasant: __sdk::TableAppliedDiff<'r, Peasant>,
    pet_component: __sdk::TableAppliedDiff<'r, PetComponent>,
    player: __sdk::TableAppliedDiff<'r, Player>,
    player_perspective: __sdk::TableAppliedDiff<'r, PlayerPerspective>,
    player_session: __sdk::TableAppliedDiff<'r, PlayerSession>,
    resource_node: __sdk::TableAppliedDiff<'r, ResourceNode>,
    structure: __sdk::TableAppliedDiff<'r, Structure>,
    transform: __sdk::TableAppliedDiff<'r, Transform>,
    waypoint: __sdk::TableAppliedDiff<'r, Waypoint>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<CombatEvent>(
            "combat_event",
            &self.combat_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<FactionComponent>(
            "faction_component",
            &self.faction_component,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GlobalState>(
            "global_state",
            &self.global_state,
            event,
        );
        callbacks.invoke_table_row_callbacks::<HarvestableCorpse>(
            "harvestable_corpse",
            &self.harvestable_corpse,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Health>("health", &self.health, event);
        callbacks.invoke_table_row_callbacks::<HitboxHistory>(
            "hitbox_history",
            &self.hitbox_history,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Inventory>("inventory", &self.inventory, event);
        callbacks.invoke_table_row_callbacks::<NavEvent>("nav_event", &self.nav_event, event);
        callbacks.invoke_table_row_callbacks::<NpcBrain>("npc_brain", &self.npc_brain, event);
        callbacks.invoke_table_row_callbacks::<Peasant>("peasant", &self.peasant, event);
        callbacks.invoke_table_row_callbacks::<PetComponent>(
            "pet_component",
            &self.pet_component,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Player>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<PlayerPerspective>(
            "player_perspective",
            &self.player_perspective,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlayerSession>(
            "player_session",
            &self.player_session,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ResourceNode>(
            "resource_node",
            &self.resource_node,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Structure>("structure", &self.structure, event);
        callbacks.invoke_table_row_callbacks::<Transform>("transform", &self.transform, event);
        callbacks.invoke_table_row_callbacks::<Waypoint>("waypoint", &self.waypoint, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        combat_event_table::register_table(client_cache);
        faction_component_table::register_table(client_cache);
        global_state_table::register_table(client_cache);
        harvestable_corpse_table::register_table(client_cache);
        health_table::register_table(client_cache);
        hitbox_history_table::register_table(client_cache);
        inventory_table::register_table(client_cache);
        nav_event_table::register_table(client_cache);
        npc_brain_table::register_table(client_cache);
        peasant_table::register_table(client_cache);
        pet_component_table::register_table(client_cache);
        player_table::register_table(client_cache);
        player_perspective_table::register_table(client_cache);
        player_session_table::register_table(client_cache);
        resource_node_table::register_table(client_cache);
        structure_table::register_table(client_cache);
        transform_table::register_table(client_cache);
        waypoint_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "combat_event",
        "faction_component",
        "global_state",
        "harvestable_corpse",
        "health",
        "hitbox_history",
        "inventory",
        "nav_event",
        "npc_brain",
        "peasant",
        "pet_component",
        "player",
        "player_perspective",
        "player_session",
        "resource_node",
        "structure",
        "transform",
        "waypoint",
    ];
}
