// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::nav_event_type::NavEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `nav_event`.
///
/// Obtain a handle from the [`NavEventTableAccess::nav_event`] method on [`super::RemoteTables`],
/// like `ctx.db.nav_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.nav_event().on_insert(...)`.
pub struct NavEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<NavEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `nav_event`.
pub struct NavEventTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for NavEventTableAccessor {
    type Row = NavEvent;
    type Handle<'db> = NavEventTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.nav_event()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `nav_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NavEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NavEventTableHandle`], which mediates access to the table `nav_event`.
    fn nav_event(&self) -> NavEventTableHandle<'_>;
}

impl NavEventTableAccess for super::RemoteTables {
    fn nav_event(&self) -> NavEventTableHandle<'_> {
        NavEventTableHandle {
            imp: self.imp.get_table::<NavEvent>("nav_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NavEventInsertCallbackId(__sdk::CallbackId);
pub struct NavEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for NavEventTableHandle<'ctx> {
    type Row = NavEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NavEvent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for NavEventTableHandle<'ctx> {
    type Row = NavEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NavEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NavEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NavEventInsertCallbackId {
        NavEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NavEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NavEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NavEventDeleteCallbackId {
        NavEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NavEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for NavEventTableHandle<'ctx> {
    type InsertCallbackId = NavEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NavEventInsertCallbackId {
        NavEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NavEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for NavEventTableHandle<'ctx> {
    type DeleteCallbackId = NavEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NavEventDeleteCallbackId {
        NavEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NavEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NavEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NavEventTableHandle<'ctx> {
    type UpdateCallbackId = NavEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NavEventUpdateCallbackId {
        NavEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NavEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for NavEventTableHandle<'ctx> {
    type UpdateCallbackId = NavEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NavEventUpdateCallbackId {
        NavEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NavEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `nav_event`,
/// which allows point queries on the field of the same name
/// via the [`NavEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.nav_event().id().find(...)`.
pub struct NavEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NavEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NavEventTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `nav_event`.
    pub fn id(&self) -> NavEventIdUnique<'ctx> {
        NavEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NavEventIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NavEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NavEvent>("nav_event");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NavEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NavEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NavEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait nav_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NavEvent`.
    fn nav_event(&self) -> __sdk::__query_builder::Table<NavEvent>;
}

impl nav_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn nav_event(&self) -> __sdk::__query_builder::Table<NavEvent> {
        __sdk::__query_builder::Table::new("nav_event")
    }
}
