// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NodeFacing {
    pub node_id: u64,
    pub dir_x: f32,
    pub dir_z: f32,
}

impl __sdk::InModule for NodeFacing {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NodeFacing`.
///
/// Provides typed access to columns for query building.
pub struct NodeFacingCols {
    pub node_id: __sdk::__query_builder::Col<NodeFacing, u64>,
    pub dir_x: __sdk::__query_builder::Col<NodeFacing, f32>,
    pub dir_z: __sdk::__query_builder::Col<NodeFacing, f32>,
}

impl __sdk::__query_builder::HasCols for NodeFacing {
    type Cols = NodeFacingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NodeFacingCols {
            node_id: __sdk::__query_builder::Col::new(table_name, "node_id"),
            dir_x: __sdk::__query_builder::Col::new(table_name, "dir_x"),
            dir_z: __sdk::__query_builder::Col::new(table_name, "dir_z"),
        }
    }
}

/// Indexed column accessor struct for the table `NodeFacing`.
///
/// Provides typed access to indexed columns for query building.
pub struct NodeFacingIxCols {
    pub node_id: __sdk::__query_builder::IxCol<NodeFacing, u64>,
}

impl __sdk::__query_builder::HasIxCols for NodeFacing {
    type IxCols = NodeFacingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NodeFacingIxCols {
            node_id: __sdk::__query_builder::IxCol::new(table_name, "node_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NodeFacing {}
