// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::node_facing_type::NodeFacing;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `node_facing`.
///
/// Obtain a handle from the [`NodeFacingTableAccess::node_facing`] method on [`super::RemoteTables`],
/// like `ctx.db.node_facing()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.node_facing().on_insert(...)`.
pub struct NodeFacingTableHandle<'ctx> {
    imp: __sdk::TableHandle<NodeFacing>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `node_facing`.
pub struct NodeFacingTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for NodeFacingTableAccessor {
    type Row = NodeFacing;
    type Handle<'db> = NodeFacingTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.node_facing()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `node_facing`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NodeFacingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NodeFacingTableHandle`], which mediates access to the table `node_facing`.
    fn node_facing(&self) -> NodeFacingTableHandle<'_>;
}

impl NodeFacingTableAccess for super::RemoteTables {
    fn node_facing(&self) -> NodeFacingTableHandle<'_> {
        NodeFacingTableHandle {
            imp: self.imp.get_table::<NodeFacing>("node_facing"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NodeFacingInsertCallbackId(__sdk::CallbackId);
pub struct NodeFacingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for NodeFacingTableHandle<'ctx> {
    type Row = NodeFacing;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NodeFacing> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for NodeFacingTableHandle<'ctx> {
    type Row = NodeFacing;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NodeFacing> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NodeFacingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeFacingInsertCallbackId {
        NodeFacingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NodeFacingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NodeFacingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeFacingDeleteCallbackId {
        NodeFacingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NodeFacingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for NodeFacingTableHandle<'ctx> {
    type InsertCallbackId = NodeFacingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeFacingInsertCallbackId {
        NodeFacingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NodeFacingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for NodeFacingTableHandle<'ctx> {
    type DeleteCallbackId = NodeFacingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NodeFacingDeleteCallbackId {
        NodeFacingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NodeFacingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NodeFacingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NodeFacingTableHandle<'ctx> {
    type UpdateCallbackId = NodeFacingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NodeFacingUpdateCallbackId {
        NodeFacingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NodeFacingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for NodeFacingTableHandle<'ctx> {
    type UpdateCallbackId = NodeFacingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NodeFacingUpdateCallbackId {
        NodeFacingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NodeFacingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `node_id` unique index on the table `node_facing`,
/// which allows point queries on the field of the same name
/// via the [`NodeFacingNodeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.node_facing().node_id().find(...)`.
pub struct NodeFacingNodeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NodeFacing, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NodeFacingTableHandle<'ctx> {
    /// Get a handle on the `node_id` unique index on the table `node_facing`.
    pub fn node_id(&self) -> NodeFacingNodeIdUnique<'ctx> {
        NodeFacingNodeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("node_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NodeFacingNodeIdUnique<'ctx> {
    /// Find the subscribed row whose `node_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NodeFacing> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NodeFacing>("node_facing");
    _table.add_unique_constraint::<u64>("node_id", |row| &row.node_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NodeFacing>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NodeFacing>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NodeFacing`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait node_facingQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NodeFacing`.
    fn node_facing(&self) -> __sdk::__query_builder::Table<NodeFacing>;
}

impl node_facingQueryTableAccess for __sdk::QueryTableAccessor {
    fn node_facing(&self) -> __sdk::__query_builder::Table<NodeFacing> {
        __sdk::__query_builder::Table::new("node_facing")
    }
}
