// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ai_type_type::AiType;
use super::brain_state_type::BrainState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcBrain {
    pub entity_id: u64,
    pub ai_type: AiType,
    pub state: BrainState,
    pub target_id: Option<u64>,
    pub timer: f32,
    pub home_x: f32,
    pub home_z: f32,
    pub wander_x: f32,
    pub wander_z: f32,
}

impl __sdk::InModule for NpcBrain {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcBrain`.
///
/// Provides typed access to columns for query building.
pub struct NpcBrainCols {
    pub entity_id: __sdk::__query_builder::Col<NpcBrain, u64>,
    pub ai_type: __sdk::__query_builder::Col<NpcBrain, AiType>,
    pub state: __sdk::__query_builder::Col<NpcBrain, BrainState>,
    pub target_id: __sdk::__query_builder::Col<NpcBrain, Option<u64>>,
    pub timer: __sdk::__query_builder::Col<NpcBrain, f32>,
    pub home_x: __sdk::__query_builder::Col<NpcBrain, f32>,
    pub home_z: __sdk::__query_builder::Col<NpcBrain, f32>,
    pub wander_x: __sdk::__query_builder::Col<NpcBrain, f32>,
    pub wander_z: __sdk::__query_builder::Col<NpcBrain, f32>,
}

impl __sdk::__query_builder::HasCols for NpcBrain {
    type Cols = NpcBrainCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcBrainCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            ai_type: __sdk::__query_builder::Col::new(table_name, "ai_type"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            target_id: __sdk::__query_builder::Col::new(table_name, "target_id"),
            timer: __sdk::__query_builder::Col::new(table_name, "timer"),
            home_x: __sdk::__query_builder::Col::new(table_name, "home_x"),
            home_z: __sdk::__query_builder::Col::new(table_name, "home_z"),
            wander_x: __sdk::__query_builder::Col::new(table_name, "wander_x"),
            wander_z: __sdk::__query_builder::Col::new(table_name, "wander_z"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcBrain`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcBrainIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<NpcBrain, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcBrain {
    type IxCols = NpcBrainIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcBrainIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcBrain {}
