// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::pet_component_type::PetComponent;
use super::pet_stance_type::PetStance;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `pet_component`.
///
/// Obtain a handle from the [`PetComponentTableAccess::pet_component`] method on [`super::RemoteTables`],
/// like `ctx.db.pet_component()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pet_component().on_insert(...)`.
pub struct PetComponentTableHandle<'ctx> {
    imp: __sdk::TableHandle<PetComponent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `pet_component`.
pub struct PetComponentTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PetComponentTableAccessor {
    type Row = PetComponent;
    type Handle<'db> = PetComponentTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.pet_component()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pet_component`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PetComponentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PetComponentTableHandle`], which mediates access to the table `pet_component`.
    fn pet_component(&self) -> PetComponentTableHandle<'_>;
}

impl PetComponentTableAccess for super::RemoteTables {
    fn pet_component(&self) -> PetComponentTableHandle<'_> {
        PetComponentTableHandle {
            imp: self.imp.get_table::<PetComponent>("pet_component"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PetComponentInsertCallbackId(__sdk::CallbackId);
pub struct PetComponentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PetComponentTableHandle<'ctx> {
    type Row = PetComponent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PetComponent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PetComponentTableHandle<'ctx> {
    type Row = PetComponent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PetComponent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PetComponentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PetComponentInsertCallbackId {
        PetComponentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PetComponentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PetComponentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PetComponentDeleteCallbackId {
        PetComponentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PetComponentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PetComponentTableHandle<'ctx> {
    type InsertCallbackId = PetComponentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PetComponentInsertCallbackId {
        PetComponentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PetComponentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PetComponentTableHandle<'ctx> {
    type DeleteCallbackId = PetComponentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PetComponentDeleteCallbackId {
        PetComponentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PetComponentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PetComponentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PetComponentTableHandle<'ctx> {
    type UpdateCallbackId = PetComponentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PetComponentUpdateCallbackId {
        PetComponentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PetComponentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PetComponentTableHandle<'ctx> {
    type UpdateCallbackId = PetComponentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PetComponentUpdateCallbackId {
        PetComponentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PetComponentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `pet_component`,
/// which allows point queries on the field of the same name
/// via the [`PetComponentEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pet_component().entity_id().find(...)`.
pub struct PetComponentEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PetComponent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PetComponentTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `pet_component`.
    pub fn entity_id(&self) -> PetComponentEntityIdUnique<'ctx> {
        PetComponentEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PetComponentEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PetComponent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PetComponent>("pet_component");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PetComponent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PetComponent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PetComponent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait pet_componentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PetComponent`.
    fn pet_component(&self) -> __sdk::__query_builder::Table<PetComponent>;
}

impl pet_componentQueryTableAccess for __sdk::QueryTableAccessor {
    fn pet_component(&self) -> __sdk::__query_builder::Table<PetComponent> {
        __sdk::__query_builder::Table::new("pet_component")
    }
}
