// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlaceStructureArgs {
    pub piece_type: String,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub rot_x: f32,
    pub rot_y: f32,
    pub rot_z: f32,
    pub rot_w: f32,
}

impl From<PlaceStructureArgs> for super::Reducer {
    fn from(args: PlaceStructureArgs) -> Self {
        Self::PlaceStructure {
            piece_type: args.piece_type,
            x: args.x,
            y: args.y,
            z: args.z,
            rot_x: args.rot_x,
            rot_y: args.rot_y,
            rot_z: args.rot_z,
            rot_w: args.rot_w,
        }
    }
}

impl __sdk::InModule for PlaceStructureArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `place_structure`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait place_structure {
    /// Request that the remote module invoke the reducer `place_structure` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`place_structure:place_structure_then`] to run a callback after the reducer completes.
    fn place_structure(
        &self,
        piece_type: String,
        x: f32,
        y: f32,
        z: f32,
        rot_x: f32,
        rot_y: f32,
        rot_z: f32,
        rot_w: f32,
    ) -> __sdk::Result<()> {
        self.place_structure_then(piece_type, x, y, z, rot_x, rot_y, rot_z, rot_w, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `place_structure` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn place_structure_then(
        &self,
        piece_type: String,
        x: f32,
        y: f32,
        z: f32,
        rot_x: f32,
        rot_y: f32,
        rot_z: f32,
        rot_w: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl place_structure for super::RemoteReducers {
    fn place_structure_then(
        &self,
        piece_type: String,
        x: f32,
        y: f32,
        z: f32,
        rot_x: f32,
        rot_y: f32,
        rot_z: f32,
        rot_w: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PlaceStructureArgs {
                piece_type,
                x,
                y,
                z,
                rot_x,
                rot_y,
                rot_z,
                rot_w,
            },
            callback,
        )
    }
}
