// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerPerspective {
    pub entity_id: u64,
    pub camera_mode: String,
}

impl __sdk::InModule for PlayerPerspective {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerPerspective`.
///
/// Provides typed access to columns for query building.
pub struct PlayerPerspectiveCols {
    pub entity_id: __sdk::__query_builder::Col<PlayerPerspective, u64>,
    pub camera_mode: __sdk::__query_builder::Col<PlayerPerspective, String>,
}

impl __sdk::__query_builder::HasCols for PlayerPerspective {
    type Cols = PlayerPerspectiveCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerPerspectiveCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            camera_mode: __sdk::__query_builder::Col::new(table_name, "camera_mode"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerPerspective`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerPerspectiveIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PlayerPerspective, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlayerPerspective {
    type IxCols = PlayerPerspectiveIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerPerspectiveIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerPerspective {}
