// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::recipe_definition_type::RecipeDefinition;
use super::recipe_ingredient_type::RecipeIngredient;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `recipe_definition`.
///
/// Obtain a handle from the [`RecipeDefinitionTableAccess::recipe_definition`] method on [`super::RemoteTables`],
/// like `ctx.db.recipe_definition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.recipe_definition().on_insert(...)`.
pub struct RecipeDefinitionTableHandle<'ctx> {
    imp: __sdk::TableHandle<RecipeDefinition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `recipe_definition`.
pub struct RecipeDefinitionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for RecipeDefinitionTableAccessor {
    type Row = RecipeDefinition;
    type Handle<'db> = RecipeDefinitionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.recipe_definition()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `recipe_definition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RecipeDefinitionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RecipeDefinitionTableHandle`], which mediates access to the table `recipe_definition`.
    fn recipe_definition(&self) -> RecipeDefinitionTableHandle<'_>;
}

impl RecipeDefinitionTableAccess for super::RemoteTables {
    fn recipe_definition(&self) -> RecipeDefinitionTableHandle<'_> {
        RecipeDefinitionTableHandle {
            imp: self.imp.get_table::<RecipeDefinition>("recipe_definition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RecipeDefinitionInsertCallbackId(__sdk::CallbackId);
pub struct RecipeDefinitionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RecipeDefinitionTableHandle<'ctx> {
    type Row = RecipeDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RecipeDefinition> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for RecipeDefinitionTableHandle<'ctx> {
    type Row = RecipeDefinition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RecipeDefinition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RecipeDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeDefinitionInsertCallbackId {
        RecipeDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RecipeDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RecipeDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeDefinitionDeleteCallbackId {
        RecipeDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RecipeDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RecipeDefinitionTableHandle<'ctx> {
    type InsertCallbackId = RecipeDefinitionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeDefinitionInsertCallbackId {
        RecipeDefinitionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RecipeDefinitionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RecipeDefinitionTableHandle<'ctx> {
    type DeleteCallbackId = RecipeDefinitionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RecipeDefinitionDeleteCallbackId {
        RecipeDefinitionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RecipeDefinitionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RecipeDefinitionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RecipeDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = RecipeDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RecipeDefinitionUpdateCallbackId {
        RecipeDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RecipeDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RecipeDefinitionTableHandle<'ctx> {
    type UpdateCallbackId = RecipeDefinitionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RecipeDefinitionUpdateCallbackId {
        RecipeDefinitionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RecipeDefinitionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `recipe_id` unique index on the table `recipe_definition`,
/// which allows point queries on the field of the same name
/// via the [`RecipeDefinitionRecipeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.recipe_definition().recipe_id().find(...)`.
pub struct RecipeDefinitionRecipeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RecipeDefinition, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RecipeDefinitionTableHandle<'ctx> {
    /// Get a handle on the `recipe_id` unique index on the table `recipe_definition`.
    pub fn recipe_id(&self) -> RecipeDefinitionRecipeIdUnique<'ctx> {
        RecipeDefinitionRecipeIdUnique {
            imp: self.imp.get_unique_constraint::<String>("recipe_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RecipeDefinitionRecipeIdUnique<'ctx> {
    /// Find the subscribed row whose `recipe_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<RecipeDefinition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RecipeDefinition>("recipe_definition");
    _table.add_unique_constraint::<String>("recipe_id", |row| &row.recipe_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RecipeDefinition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RecipeDefinition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RecipeDefinition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait recipe_definitionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RecipeDefinition`.
    fn recipe_definition(&self) -> __sdk::__query_builder::Table<RecipeDefinition>;
}

impl recipe_definitionQueryTableAccess for __sdk::QueryTableAccessor {
    fn recipe_definition(&self) -> __sdk::__query_builder::Table<RecipeDefinition> {
        __sdk::__query_builder::Table::new("recipe_definition")
    }
}
