// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::resource_node_type::ResourceNode;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `resource_node`.
///
/// Obtain a handle from the [`ResourceNodeTableAccess::resource_node`] method on [`super::RemoteTables`],
/// like `ctx.db.resource_node()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_node().on_insert(...)`.
pub struct ResourceNodeTableHandle<'ctx> {
    imp: __sdk::TableHandle<ResourceNode>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `resource_node`.
pub struct ResourceNodeTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ResourceNodeTableAccessor {
    type Row = ResourceNode;
    type Handle<'db> = ResourceNodeTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.resource_node()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `resource_node`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ResourceNodeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ResourceNodeTableHandle`], which mediates access to the table `resource_node`.
    fn resource_node(&self) -> ResourceNodeTableHandle<'_>;
}

impl ResourceNodeTableAccess for super::RemoteTables {
    fn resource_node(&self) -> ResourceNodeTableHandle<'_> {
        ResourceNodeTableHandle {
            imp: self.imp.get_table::<ResourceNode>("resource_node"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ResourceNodeInsertCallbackId(__sdk::CallbackId);
pub struct ResourceNodeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ResourceNodeTableHandle<'ctx> {
    type Row = ResourceNode;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ResourceNode> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ResourceNodeTableHandle<'ctx> {
    type Row = ResourceNode;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ResourceNode> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ResourceNodeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceNodeInsertCallbackId {
        ResourceNodeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ResourceNodeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ResourceNodeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceNodeDeleteCallbackId {
        ResourceNodeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ResourceNodeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ResourceNodeTableHandle<'ctx> {
    type InsertCallbackId = ResourceNodeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceNodeInsertCallbackId {
        ResourceNodeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ResourceNodeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ResourceNodeTableHandle<'ctx> {
    type DeleteCallbackId = ResourceNodeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceNodeDeleteCallbackId {
        ResourceNodeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ResourceNodeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ResourceNodeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ResourceNodeTableHandle<'ctx> {
    type UpdateCallbackId = ResourceNodeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ResourceNodeUpdateCallbackId {
        ResourceNodeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ResourceNodeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ResourceNodeTableHandle<'ctx> {
    type UpdateCallbackId = ResourceNodeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ResourceNodeUpdateCallbackId {
        ResourceNodeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ResourceNodeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `node_id` unique index on the table `resource_node`,
/// which allows point queries on the field of the same name
/// via the [`ResourceNodeNodeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_node().node_id().find(...)`.
pub struct ResourceNodeNodeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ResourceNode, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ResourceNodeTableHandle<'ctx> {
    /// Get a handle on the `node_id` unique index on the table `resource_node`.
    pub fn node_id(&self) -> ResourceNodeNodeIdUnique<'ctx> {
        ResourceNodeNodeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("node_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ResourceNodeNodeIdUnique<'ctx> {
    /// Find the subscribed row whose `node_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ResourceNode> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ResourceNode>("resource_node");
    _table.add_unique_constraint::<u64>("node_id", |row| &row.node_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ResourceNode>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ResourceNode>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ResourceNode`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait resource_nodeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ResourceNode`.
    fn resource_node(&self) -> __sdk::__query_builder::Table<ResourceNode>;
}

impl resource_nodeQueryTableAccess for __sdk::QueryTableAccessor {
    fn resource_node(&self) -> __sdk::__query_builder::Table<ResourceNode> {
        __sdk::__query_builder::Table::new("resource_node")
    }
}
