// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::resource_stockpile_type::ResourceStockpile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `resource_stockpile`.
///
/// Obtain a handle from the [`ResourceStockpileTableAccess::resource_stockpile`] method on [`super::RemoteTables`],
/// like `ctx.db.resource_stockpile()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_stockpile().on_insert(...)`.
pub struct ResourceStockpileTableHandle<'ctx> {
    imp: __sdk::TableHandle<ResourceStockpile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `resource_stockpile`.
pub struct ResourceStockpileTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ResourceStockpileTableAccessor {
    type Row = ResourceStockpile;
    type Handle<'db> = ResourceStockpileTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.resource_stockpile()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `resource_stockpile`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ResourceStockpileTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ResourceStockpileTableHandle`], which mediates access to the table `resource_stockpile`.
    fn resource_stockpile(&self) -> ResourceStockpileTableHandle<'_>;
}

impl ResourceStockpileTableAccess for super::RemoteTables {
    fn resource_stockpile(&self) -> ResourceStockpileTableHandle<'_> {
        ResourceStockpileTableHandle {
            imp: self
                .imp
                .get_table::<ResourceStockpile>("resource_stockpile"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ResourceStockpileInsertCallbackId(__sdk::CallbackId);
pub struct ResourceStockpileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ResourceStockpileTableHandle<'ctx> {
    type Row = ResourceStockpile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ResourceStockpile> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ResourceStockpileTableHandle<'ctx> {
    type Row = ResourceStockpile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ResourceStockpile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ResourceStockpileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceStockpileInsertCallbackId {
        ResourceStockpileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ResourceStockpileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ResourceStockpileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceStockpileDeleteCallbackId {
        ResourceStockpileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ResourceStockpileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ResourceStockpileTableHandle<'ctx> {
    type InsertCallbackId = ResourceStockpileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceStockpileInsertCallbackId {
        ResourceStockpileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ResourceStockpileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ResourceStockpileTableHandle<'ctx> {
    type DeleteCallbackId = ResourceStockpileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceStockpileDeleteCallbackId {
        ResourceStockpileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ResourceStockpileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ResourceStockpileUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ResourceStockpileTableHandle<'ctx> {
    type UpdateCallbackId = ResourceStockpileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ResourceStockpileUpdateCallbackId {
        ResourceStockpileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ResourceStockpileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ResourceStockpileTableHandle<'ctx> {
    type UpdateCallbackId = ResourceStockpileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ResourceStockpileUpdateCallbackId {
        ResourceStockpileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ResourceStockpileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `resource_stockpile`,
/// which allows point queries on the field of the same name
/// via the [`ResourceStockpileEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_stockpile().entity_id().find(...)`.
pub struct ResourceStockpileEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ResourceStockpile, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ResourceStockpileTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `resource_stockpile`.
    pub fn entity_id(&self) -> ResourceStockpileEntityIdUnique<'ctx> {
        ResourceStockpileEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ResourceStockpileEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ResourceStockpile> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ResourceStockpile>("resource_stockpile");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ResourceStockpile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ResourceStockpile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ResourceStockpile`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait resource_stockpileQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ResourceStockpile`.
    fn resource_stockpile(&self) -> __sdk::__query_builder::Table<ResourceStockpile>;
}

impl resource_stockpileQueryTableAccess for __sdk::QueryTableAccessor {
    fn resource_stockpile(&self) -> __sdk::__query_builder::Table<ResourceStockpile> {
        __sdk::__query_builder::Table::new("resource_stockpile")
    }
}
