// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ResourceStockpile {
    pub entity_id: u64,
    pub wood: u32,
    pub ore: u32,
    pub food: u32,
}

impl __sdk::InModule for ResourceStockpile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ResourceStockpile`.
///
/// Provides typed access to columns for query building.
pub struct ResourceStockpileCols {
    pub entity_id: __sdk::__query_builder::Col<ResourceStockpile, u64>,
    pub wood: __sdk::__query_builder::Col<ResourceStockpile, u32>,
    pub ore: __sdk::__query_builder::Col<ResourceStockpile, u32>,
    pub food: __sdk::__query_builder::Col<ResourceStockpile, u32>,
}

impl __sdk::__query_builder::HasCols for ResourceStockpile {
    type Cols = ResourceStockpileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ResourceStockpileCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            wood: __sdk::__query_builder::Col::new(table_name, "wood"),
            ore: __sdk::__query_builder::Col::new(table_name, "ore"),
            food: __sdk::__query_builder::Col::new(table_name, "food"),
        }
    }
}

/// Indexed column accessor struct for the table `ResourceStockpile`.
///
/// Provides typed access to indexed columns for query building.
pub struct ResourceStockpileIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<ResourceStockpile, u64>,
}

impl __sdk::__query_builder::HasIxCols for ResourceStockpile {
    type IxCols = ResourceStockpileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ResourceStockpileIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ResourceStockpile {}
