// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RockExcavationState {
    pub rock_key: u64,
    pub hits_taken: u32,
    pub last_hit_tick: u64,
}

impl __sdk::InModule for RockExcavationState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RockExcavationState`.
///
/// Provides typed access to columns for query building.
pub struct RockExcavationStateCols {
    pub rock_key: __sdk::__query_builder::Col<RockExcavationState, u64>,
    pub hits_taken: __sdk::__query_builder::Col<RockExcavationState, u32>,
    pub last_hit_tick: __sdk::__query_builder::Col<RockExcavationState, u64>,
}

impl __sdk::__query_builder::HasCols for RockExcavationState {
    type Cols = RockExcavationStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RockExcavationStateCols {
            rock_key: __sdk::__query_builder::Col::new(table_name, "rock_key"),
            hits_taken: __sdk::__query_builder::Col::new(table_name, "hits_taken"),
            last_hit_tick: __sdk::__query_builder::Col::new(table_name, "last_hit_tick"),
        }
    }
}

/// Indexed column accessor struct for the table `RockExcavationState`.
///
/// Provides typed access to indexed columns for query building.
pub struct RockExcavationStateIxCols {
    pub rock_key: __sdk::__query_builder::IxCol<RockExcavationState, u64>,
}

impl __sdk::__query_builder::HasIxCols for RockExcavationState {
    type IxCols = RockExcavationStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RockExcavationStateIxCols {
            rock_key: __sdk::__query_builder::IxCol::new(table_name, "rock_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RockExcavationState {}
