// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnTemplateBlueprintArgs {
    pub template_name: String,
    pub faction_name: String,
    pub origin_x: f32,
    pub origin_z: f32,
}

impl From<SpawnTemplateBlueprintArgs> for super::Reducer {
    fn from(args: SpawnTemplateBlueprintArgs) -> Self {
        Self::SpawnTemplateBlueprint {
            template_name: args.template_name,
            faction_name: args.faction_name,
            origin_x: args.origin_x,
            origin_z: args.origin_z,
        }
    }
}

impl __sdk::InModule for SpawnTemplateBlueprintArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_template_blueprint`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_template_blueprint {
    /// Request that the remote module invoke the reducer `spawn_template_blueprint` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn_template_blueprint:spawn_template_blueprint_then`] to run a callback after the reducer completes.
    fn spawn_template_blueprint(
        &self,
        template_name: String,
        faction_name: String,
        origin_x: f32,
        origin_z: f32,
    ) -> __sdk::Result<()> {
        self.spawn_template_blueprint_then(template_name, faction_name, origin_x, origin_z, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `spawn_template_blueprint` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_template_blueprint_then(
        &self,
        template_name: String,
        faction_name: String,
        origin_x: f32,
        origin_z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn_template_blueprint for super::RemoteReducers {
    fn spawn_template_blueprint_then(
        &self,
        template_name: String,
        faction_name: String,
        origin_x: f32,
        origin_z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(
                SpawnTemplateBlueprintArgs {
                    template_name,
                    faction_name,
                    origin_x,
                    origin_z,
                },
                callback,
            )
    }
}
