// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::structure_edge_type::StructureEdge;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `structure_edge`.
///
/// Obtain a handle from the [`StructureEdgeTableAccess::structure_edge`] method on [`super::RemoteTables`],
/// like `ctx.db.structure_edge()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.structure_edge().on_insert(...)`.
pub struct StructureEdgeTableHandle<'ctx> {
    imp: __sdk::TableHandle<StructureEdge>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `structure_edge`.
pub struct StructureEdgeTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for StructureEdgeTableAccessor {
    type Row = StructureEdge;
    type Handle<'db> = StructureEdgeTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.structure_edge()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `structure_edge`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StructureEdgeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StructureEdgeTableHandle`], which mediates access to the table `structure_edge`.
    fn structure_edge(&self) -> StructureEdgeTableHandle<'_>;
}

impl StructureEdgeTableAccess for super::RemoteTables {
    fn structure_edge(&self) -> StructureEdgeTableHandle<'_> {
        StructureEdgeTableHandle {
            imp: self.imp.get_table::<StructureEdge>("structure_edge"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StructureEdgeInsertCallbackId(__sdk::CallbackId);
pub struct StructureEdgeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for StructureEdgeTableHandle<'ctx> {
    type Row = StructureEdge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StructureEdge> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for StructureEdgeTableHandle<'ctx> {
    type Row = StructureEdge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StructureEdge> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StructureEdgeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StructureEdgeInsertCallbackId {
        StructureEdgeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StructureEdgeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StructureEdgeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StructureEdgeDeleteCallbackId {
        StructureEdgeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StructureEdgeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for StructureEdgeTableHandle<'ctx> {
    type InsertCallbackId = StructureEdgeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StructureEdgeInsertCallbackId {
        StructureEdgeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StructureEdgeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for StructureEdgeTableHandle<'ctx> {
    type DeleteCallbackId = StructureEdgeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StructureEdgeDeleteCallbackId {
        StructureEdgeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StructureEdgeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct StructureEdgeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StructureEdgeTableHandle<'ctx> {
    type UpdateCallbackId = StructureEdgeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StructureEdgeUpdateCallbackId {
        StructureEdgeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StructureEdgeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for StructureEdgeTableHandle<'ctx> {
    type UpdateCallbackId = StructureEdgeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StructureEdgeUpdateCallbackId {
        StructureEdgeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StructureEdgeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `edge_id` unique index on the table `structure_edge`,
/// which allows point queries on the field of the same name
/// via the [`StructureEdgeEdgeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.structure_edge().edge_id().find(...)`.
pub struct StructureEdgeEdgeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StructureEdge, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StructureEdgeTableHandle<'ctx> {
    /// Get a handle on the `edge_id` unique index on the table `structure_edge`.
    pub fn edge_id(&self) -> StructureEdgeEdgeIdUnique<'ctx> {
        StructureEdgeEdgeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("edge_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StructureEdgeEdgeIdUnique<'ctx> {
    /// Find the subscribed row whose `edge_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StructureEdge> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StructureEdge>("structure_edge");
    _table.add_unique_constraint::<u64>("edge_id", |row| &row.edge_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<StructureEdge>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StructureEdge>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `StructureEdge`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait structure_edgeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `StructureEdge`.
    fn structure_edge(&self) -> __sdk::__query_builder::Table<StructureEdge>;
}

impl structure_edgeQueryTableAccess for __sdk::QueryTableAccessor {
    fn structure_edge(&self) -> __sdk::__query_builder::Table<StructureEdge> {
        __sdk::__query_builder::Table::new("structure_edge")
    }
}
