// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StructureEdge {
    pub edge_id: u64,
    pub parent_id: u64,
    pub child_id: u64,
    pub distance_h: f32,
    pub distance_v: f32,
}

impl __sdk::InModule for StructureEdge {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StructureEdge`.
///
/// Provides typed access to columns for query building.
pub struct StructureEdgeCols {
    pub edge_id: __sdk::__query_builder::Col<StructureEdge, u64>,
    pub parent_id: __sdk::__query_builder::Col<StructureEdge, u64>,
    pub child_id: __sdk::__query_builder::Col<StructureEdge, u64>,
    pub distance_h: __sdk::__query_builder::Col<StructureEdge, f32>,
    pub distance_v: __sdk::__query_builder::Col<StructureEdge, f32>,
}

impl __sdk::__query_builder::HasCols for StructureEdge {
    type Cols = StructureEdgeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StructureEdgeCols {
            edge_id: __sdk::__query_builder::Col::new(table_name, "edge_id"),
            parent_id: __sdk::__query_builder::Col::new(table_name, "parent_id"),
            child_id: __sdk::__query_builder::Col::new(table_name, "child_id"),
            distance_h: __sdk::__query_builder::Col::new(table_name, "distance_h"),
            distance_v: __sdk::__query_builder::Col::new(table_name, "distance_v"),
        }
    }
}

/// Indexed column accessor struct for the table `StructureEdge`.
///
/// Provides typed access to indexed columns for query building.
pub struct StructureEdgeIxCols {
    pub child_id: __sdk::__query_builder::IxCol<StructureEdge, u64>,
    pub edge_id: __sdk::__query_builder::IxCol<StructureEdge, u64>,
    pub parent_id: __sdk::__query_builder::IxCol<StructureEdge, u64>,
}

impl __sdk::__query_builder::HasIxCols for StructureEdge {
    type IxCols = StructureEdgeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StructureEdgeIxCols {
            child_id: __sdk::__query_builder::IxCol::new(table_name, "child_id"),
            edge_id: __sdk::__query_builder::IxCol::new(table_name, "edge_id"),
            parent_id: __sdk::__query_builder::IxCol::new(table_name, "parent_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StructureEdge {}
