// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Structure {
    pub structure_id: u64,
    pub piece_type: String,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub rot_x: f32,
    pub rot_y: f32,
    pub rot_z: f32,
    pub rot_w: f32,
    pub owner_id: u64,
}

impl __sdk::InModule for Structure {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Structure`.
///
/// Provides typed access to columns for query building.
pub struct StructureCols {
    pub structure_id: __sdk::__query_builder::Col<Structure, u64>,
    pub piece_type: __sdk::__query_builder::Col<Structure, String>,
    pub x: __sdk::__query_builder::Col<Structure, f32>,
    pub y: __sdk::__query_builder::Col<Structure, f32>,
    pub z: __sdk::__query_builder::Col<Structure, f32>,
    pub rot_x: __sdk::__query_builder::Col<Structure, f32>,
    pub rot_y: __sdk::__query_builder::Col<Structure, f32>,
    pub rot_z: __sdk::__query_builder::Col<Structure, f32>,
    pub rot_w: __sdk::__query_builder::Col<Structure, f32>,
    pub owner_id: __sdk::__query_builder::Col<Structure, u64>,
}

impl __sdk::__query_builder::HasCols for Structure {
    type Cols = StructureCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StructureCols {
            structure_id: __sdk::__query_builder::Col::new(table_name, "structure_id"),
            piece_type: __sdk::__query_builder::Col::new(table_name, "piece_type"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            rot_x: __sdk::__query_builder::Col::new(table_name, "rot_x"),
            rot_y: __sdk::__query_builder::Col::new(table_name, "rot_y"),
            rot_z: __sdk::__query_builder::Col::new(table_name, "rot_z"),
            rot_w: __sdk::__query_builder::Col::new(table_name, "rot_w"),
            owner_id: __sdk::__query_builder::Col::new(table_name, "owner_id"),
        }
    }
}

/// Indexed column accessor struct for the table `Structure`.
///
/// Provides typed access to indexed columns for query building.
pub struct StructureIxCols {
    pub structure_id: __sdk::__query_builder::IxCol<Structure, u64>,
}

impl __sdk::__query_builder::HasIxCols for Structure {
    type IxCols = StructureIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StructureIxCols {
            structure_id: __sdk::__query_builder::IxCol::new(table_name, "structure_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Structure {}
