// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SwapInventorySlotsArgs {
    pub from_slot: u32,
    pub to_slot: u32,
}

impl From<SwapInventorySlotsArgs> for super::Reducer {
    fn from(args: SwapInventorySlotsArgs) -> Self {
        Self::SwapInventorySlots {
            from_slot: args.from_slot,
            to_slot: args.to_slot,
        }
    }
}

impl __sdk::InModule for SwapInventorySlotsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `swap_inventory_slots`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait swap_inventory_slots {
    /// Request that the remote module invoke the reducer `swap_inventory_slots` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`swap_inventory_slots:swap_inventory_slots_then`] to run a callback after the reducer completes.
    fn swap_inventory_slots(&self, from_slot: u32, to_slot: u32) -> __sdk::Result<()> {
        self.swap_inventory_slots_then(from_slot, to_slot, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `swap_inventory_slots` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn swap_inventory_slots_then(
        &self,
        from_slot: u32,
        to_slot: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl swap_inventory_slots for super::RemoteReducers {
    fn swap_inventory_slots_then(
        &self,
        from_slot: u32,
        to_slot: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SwapInventorySlotsArgs { from_slot, to_slot }, callback)
    }
}
