// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TickNpcAiArgs {
    pub npc_id: u64,
}

impl From<TickNpcAiArgs> for super::Reducer {
    fn from(args: TickNpcAiArgs) -> Self {
        Self::TickNpcAi {
            npc_id: args.npc_id,
        }
    }
}

impl __sdk::InModule for TickNpcAiArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `tick_npc_ai`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait tick_npc_ai {
    /// Request that the remote module invoke the reducer `tick_npc_ai` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`tick_npc_ai:tick_npc_ai_then`] to run a callback after the reducer completes.
    fn tick_npc_ai(&self, npc_id: u64) -> __sdk::Result<()> {
        self.tick_npc_ai_then(npc_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `tick_npc_ai` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn tick_npc_ai_then(
        &self,
        npc_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl tick_npc_ai for super::RemoteReducers {
    fn tick_npc_ai_then(
        &self,
        npc_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(TickNpcAiArgs { npc_id }, callback)
    }
}
