// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::voxel_chunk_type::VoxelChunk;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `voxel_chunk`.
///
/// Obtain a handle from the [`VoxelChunkTableAccess::voxel_chunk`] method on [`super::RemoteTables`],
/// like `ctx.db.voxel_chunk()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.voxel_chunk().on_insert(...)`.
pub struct VoxelChunkTableHandle<'ctx> {
    imp: __sdk::TableHandle<VoxelChunk>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `voxel_chunk`.
pub struct VoxelChunkTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VoxelChunkTableAccessor {
    type Row = VoxelChunk;
    type Handle<'db> = VoxelChunkTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.voxel_chunk()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `voxel_chunk`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VoxelChunkTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VoxelChunkTableHandle`], which mediates access to the table `voxel_chunk`.
    fn voxel_chunk(&self) -> VoxelChunkTableHandle<'_>;
}

impl VoxelChunkTableAccess for super::RemoteTables {
    fn voxel_chunk(&self) -> VoxelChunkTableHandle<'_> {
        VoxelChunkTableHandle {
            imp: self.imp.get_table::<VoxelChunk>("voxel_chunk"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VoxelChunkInsertCallbackId(__sdk::CallbackId);
pub struct VoxelChunkDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VoxelChunkTableHandle<'ctx> {
    type Row = VoxelChunk;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VoxelChunk> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VoxelChunkTableHandle<'ctx> {
    type Row = VoxelChunk;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VoxelChunk> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VoxelChunkInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VoxelChunkInsertCallbackId {
        VoxelChunkInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VoxelChunkInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VoxelChunkDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VoxelChunkDeleteCallbackId {
        VoxelChunkDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VoxelChunkDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VoxelChunkTableHandle<'ctx> {
    type InsertCallbackId = VoxelChunkInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VoxelChunkInsertCallbackId {
        VoxelChunkInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VoxelChunkInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VoxelChunkTableHandle<'ctx> {
    type DeleteCallbackId = VoxelChunkDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VoxelChunkDeleteCallbackId {
        VoxelChunkDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VoxelChunkDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VoxelChunkUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VoxelChunkTableHandle<'ctx> {
    type UpdateCallbackId = VoxelChunkUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VoxelChunkUpdateCallbackId {
        VoxelChunkUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VoxelChunkUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for VoxelChunkTableHandle<'ctx> {
    type UpdateCallbackId = VoxelChunkUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VoxelChunkUpdateCallbackId {
        VoxelChunkUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VoxelChunkUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `chunk_key` unique index on the table `voxel_chunk`,
/// which allows point queries on the field of the same name
/// via the [`VoxelChunkChunkKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.voxel_chunk().chunk_key().find(...)`.
pub struct VoxelChunkChunkKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<VoxelChunk, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VoxelChunkTableHandle<'ctx> {
    /// Get a handle on the `chunk_key` unique index on the table `voxel_chunk`.
    pub fn chunk_key(&self) -> VoxelChunkChunkKeyUnique<'ctx> {
        VoxelChunkChunkKeyUnique {
            imp: self.imp.get_unique_constraint::<u64>("chunk_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VoxelChunkChunkKeyUnique<'ctx> {
    /// Find the subscribed row whose `chunk_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<VoxelChunk> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VoxelChunk>("voxel_chunk");
    _table.add_unique_constraint::<u64>("chunk_key", |row| &row.chunk_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<VoxelChunk>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VoxelChunk>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `VoxelChunk`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait voxel_chunkQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `VoxelChunk`.
    fn voxel_chunk(&self) -> __sdk::__query_builder::Table<VoxelChunk>;
}

impl voxel_chunkQueryTableAccess for __sdk::QueryTableAccessor {
    fn voxel_chunk(&self) -> __sdk::__query_builder::Table<VoxelChunk> {
        __sdk::__query_builder::Table::new("voxel_chunk")
    }
}
