// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Waypoint {
    pub waypoint_id: u64,
    pub commander_id: u64,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub order_type: String,
    pub expires_at: u64,
}

impl __sdk::InModule for Waypoint {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Waypoint`.
///
/// Provides typed access to columns for query building.
pub struct WaypointCols {
    pub waypoint_id: __sdk::__query_builder::Col<Waypoint, u64>,
    pub commander_id: __sdk::__query_builder::Col<Waypoint, u64>,
    pub x: __sdk::__query_builder::Col<Waypoint, f32>,
    pub y: __sdk::__query_builder::Col<Waypoint, f32>,
    pub z: __sdk::__query_builder::Col<Waypoint, f32>,
    pub order_type: __sdk::__query_builder::Col<Waypoint, String>,
    pub expires_at: __sdk::__query_builder::Col<Waypoint, u64>,
}

impl __sdk::__query_builder::HasCols for Waypoint {
    type Cols = WaypointCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WaypointCols {
            waypoint_id: __sdk::__query_builder::Col::new(table_name, "waypoint_id"),
            commander_id: __sdk::__query_builder::Col::new(table_name, "commander_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            order_type: __sdk::__query_builder::Col::new(table_name, "order_type"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Waypoint`.
///
/// Provides typed access to indexed columns for query building.
pub struct WaypointIxCols {
    pub waypoint_id: __sdk::__query_builder::IxCol<Waypoint, u64>,
}

impl __sdk::__query_builder::HasIxCols for Waypoint {
    type IxCols = WaypointIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WaypointIxCols {
            waypoint_id: __sdk::__query_builder::IxCol::new(table_name, "waypoint_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Waypoint {}
