// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WeaponSkill {
    pub entity_id: u64,
    pub generic_physical: u32,
    pub edged_xp: u32,
    pub pointed_xp: u32,
    pub blunt_xp: u32,
    pub two_handed_xp: u32,
    pub polearm_xp: u32,
    pub brawling_xp: u32,
    pub missile_xp: u32,
    pub firearm_xp: u32,
    pub runestaff_xp: u32,
}

impl __sdk::InModule for WeaponSkill {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WeaponSkill`.
///
/// Provides typed access to columns for query building.
pub struct WeaponSkillCols {
    pub entity_id: __sdk::__query_builder::Col<WeaponSkill, u64>,
    pub generic_physical: __sdk::__query_builder::Col<WeaponSkill, u32>,
    pub edged_xp: __sdk::__query_builder::Col<WeaponSkill, u32>,
    pub pointed_xp: __sdk::__query_builder::Col<WeaponSkill, u32>,
    pub blunt_xp: __sdk::__query_builder::Col<WeaponSkill, u32>,
    pub two_handed_xp: __sdk::__query_builder::Col<WeaponSkill, u32>,
    pub polearm_xp: __sdk::__query_builder::Col<WeaponSkill, u32>,
    pub brawling_xp: __sdk::__query_builder::Col<WeaponSkill, u32>,
    pub missile_xp: __sdk::__query_builder::Col<WeaponSkill, u32>,
    pub firearm_xp: __sdk::__query_builder::Col<WeaponSkill, u32>,
    pub runestaff_xp: __sdk::__query_builder::Col<WeaponSkill, u32>,
}

impl __sdk::__query_builder::HasCols for WeaponSkill {
    type Cols = WeaponSkillCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WeaponSkillCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            generic_physical: __sdk::__query_builder::Col::new(table_name, "generic_physical"),
            edged_xp: __sdk::__query_builder::Col::new(table_name, "edged_xp"),
            pointed_xp: __sdk::__query_builder::Col::new(table_name, "pointed_xp"),
            blunt_xp: __sdk::__query_builder::Col::new(table_name, "blunt_xp"),
            two_handed_xp: __sdk::__query_builder::Col::new(table_name, "two_handed_xp"),
            polearm_xp: __sdk::__query_builder::Col::new(table_name, "polearm_xp"),
            brawling_xp: __sdk::__query_builder::Col::new(table_name, "brawling_xp"),
            missile_xp: __sdk::__query_builder::Col::new(table_name, "missile_xp"),
            firearm_xp: __sdk::__query_builder::Col::new(table_name, "firearm_xp"),
            runestaff_xp: __sdk::__query_builder::Col::new(table_name, "runestaff_xp"),
        }
    }
}

/// Indexed column accessor struct for the table `WeaponSkill`.
///
/// Provides typed access to indexed columns for query building.
pub struct WeaponSkillIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<WeaponSkill, u64>,
}

impl __sdk::__query_builder::HasIxCols for WeaponSkill {
    type IxCols = WeaponSkillIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WeaponSkillIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WeaponSkill {}
