// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::weapon_skill_type::WeaponSkill;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `weapon_skill`.
///
/// Obtain a handle from the [`WeaponSkillTableAccess::weapon_skill`] method on [`super::RemoteTables`],
/// like `ctx.db.weapon_skill()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.weapon_skill().on_insert(...)`.
pub struct WeaponSkillTableHandle<'ctx> {
    imp: __sdk::TableHandle<WeaponSkill>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `weapon_skill`.
pub struct WeaponSkillTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for WeaponSkillTableAccessor {
    type Row = WeaponSkill;
    type Handle<'db> = WeaponSkillTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.weapon_skill()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `weapon_skill`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WeaponSkillTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WeaponSkillTableHandle`], which mediates access to the table `weapon_skill`.
    fn weapon_skill(&self) -> WeaponSkillTableHandle<'_>;
}

impl WeaponSkillTableAccess for super::RemoteTables {
    fn weapon_skill(&self) -> WeaponSkillTableHandle<'_> {
        WeaponSkillTableHandle {
            imp: self.imp.get_table::<WeaponSkill>("weapon_skill"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WeaponSkillInsertCallbackId(__sdk::CallbackId);
pub struct WeaponSkillDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for WeaponSkillTableHandle<'ctx> {
    type Row = WeaponSkill;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WeaponSkill> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for WeaponSkillTableHandle<'ctx> {
    type Row = WeaponSkill;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WeaponSkill> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WeaponSkillInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WeaponSkillInsertCallbackId {
        WeaponSkillInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WeaponSkillInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WeaponSkillDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WeaponSkillDeleteCallbackId {
        WeaponSkillDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WeaponSkillDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for WeaponSkillTableHandle<'ctx> {
    type InsertCallbackId = WeaponSkillInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WeaponSkillInsertCallbackId {
        WeaponSkillInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WeaponSkillInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for WeaponSkillTableHandle<'ctx> {
    type DeleteCallbackId = WeaponSkillDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WeaponSkillDeleteCallbackId {
        WeaponSkillDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WeaponSkillDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WeaponSkillUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WeaponSkillTableHandle<'ctx> {
    type UpdateCallbackId = WeaponSkillUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WeaponSkillUpdateCallbackId {
        WeaponSkillUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WeaponSkillUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for WeaponSkillTableHandle<'ctx> {
    type UpdateCallbackId = WeaponSkillUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WeaponSkillUpdateCallbackId {
        WeaponSkillUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WeaponSkillUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `weapon_skill`,
/// which allows point queries on the field of the same name
/// via the [`WeaponSkillEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.weapon_skill().entity_id().find(...)`.
pub struct WeaponSkillEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WeaponSkill, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WeaponSkillTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `weapon_skill`.
    pub fn entity_id(&self) -> WeaponSkillEntityIdUnique<'ctx> {
        WeaponSkillEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WeaponSkillEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WeaponSkill> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WeaponSkill>("weapon_skill");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WeaponSkill>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WeaponSkill>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WeaponSkill`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait weapon_skillQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WeaponSkill`.
    fn weapon_skill(&self) -> __sdk::__query_builder::Table<WeaponSkill>;
}

impl weapon_skillQueryTableAccess for __sdk::QueryTableAccessor {
    fn weapon_skill(&self) -> __sdk::__query_builder::Table<WeaponSkill> {
        __sdk::__query_builder::Table::new("weapon_skill")
    }
}
