// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GroundLoot {
    pub loot_id: u64,
    pub item_type: String,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl __sdk::InModule for GroundLoot {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GroundLoot`.
///
/// Provides typed access to columns for query building.
pub struct GroundLootCols {
    pub loot_id: __sdk::__query_builder::Col<GroundLoot, u64>,
    pub item_type: __sdk::__query_builder::Col<GroundLoot, String>,
    pub x: __sdk::__query_builder::Col<GroundLoot, f32>,
    pub y: __sdk::__query_builder::Col<GroundLoot, f32>,
    pub z: __sdk::__query_builder::Col<GroundLoot, f32>,
}

impl __sdk::__query_builder::HasCols for GroundLoot {
    type Cols = GroundLootCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GroundLootCols {
            loot_id: __sdk::__query_builder::Col::new(table_name, "loot_id"),
            item_type: __sdk::__query_builder::Col::new(table_name, "item_type"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
        }
    }
}

/// Indexed column accessor struct for the table `GroundLoot`.
///
/// Provides typed access to indexed columns for query building.
pub struct GroundLootIxCols {
    pub loot_id: __sdk::__query_builder::IxCol<GroundLoot, u64>,
}

impl __sdk::__query_builder::HasIxCols for GroundLoot {
    type IxCols = GroundLootIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GroundLootIxCols {
            loot_id: __sdk::__query_builder::IxCol::new(table_name, "loot_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GroundLoot {}
