// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ground_loot_type::GroundLoot;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ground_loot`.
///
/// Obtain a handle from the [`GroundLootTableAccess::ground_loot`] method on [`super::RemoteTables`],
/// like `ctx.db.ground_loot()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ground_loot().on_insert(...)`.
pub struct GroundLootTableHandle<'ctx> {
    imp: __sdk::TableHandle<GroundLoot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `ground_loot`.
pub struct GroundLootTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GroundLootTableAccessor {
    type Row = GroundLoot;
    type Handle<'db> = GroundLootTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.ground_loot()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ground_loot`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GroundLootTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GroundLootTableHandle`], which mediates access to the table `ground_loot`.
    fn ground_loot(&self) -> GroundLootTableHandle<'_>;
}

impl GroundLootTableAccess for super::RemoteTables {
    fn ground_loot(&self) -> GroundLootTableHandle<'_> {
        GroundLootTableHandle {
            imp: self.imp.get_table::<GroundLoot>("ground_loot"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GroundLootInsertCallbackId(__sdk::CallbackId);
pub struct GroundLootDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GroundLootTableHandle<'ctx> {
    type Row = GroundLoot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GroundLoot> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GroundLootTableHandle<'ctx> {
    type Row = GroundLoot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GroundLoot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GroundLootInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GroundLootInsertCallbackId {
        GroundLootInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GroundLootInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GroundLootDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GroundLootDeleteCallbackId {
        GroundLootDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GroundLootDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GroundLootTableHandle<'ctx> {
    type InsertCallbackId = GroundLootInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GroundLootInsertCallbackId {
        GroundLootInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GroundLootInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GroundLootTableHandle<'ctx> {
    type DeleteCallbackId = GroundLootDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GroundLootDeleteCallbackId {
        GroundLootDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GroundLootDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GroundLootUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GroundLootTableHandle<'ctx> {
    type UpdateCallbackId = GroundLootUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GroundLootUpdateCallbackId {
        GroundLootUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GroundLootUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GroundLootTableHandle<'ctx> {
    type UpdateCallbackId = GroundLootUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GroundLootUpdateCallbackId {
        GroundLootUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GroundLootUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `loot_id` unique index on the table `ground_loot`,
/// which allows point queries on the field of the same name
/// via the [`GroundLootLootIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ground_loot().loot_id().find(...)`.
pub struct GroundLootLootIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GroundLoot, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GroundLootTableHandle<'ctx> {
    /// Get a handle on the `loot_id` unique index on the table `ground_loot`.
    pub fn loot_id(&self) -> GroundLootLootIdUnique<'ctx> {
        GroundLootLootIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("loot_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GroundLootLootIdUnique<'ctx> {
    /// Find the subscribed row whose `loot_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GroundLoot> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GroundLoot>("ground_loot");
    _table.add_unique_constraint::<u64>("loot_id", |row| &row.loot_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GroundLoot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GroundLoot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GroundLoot`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ground_lootQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GroundLoot`.
    fn ground_loot(&self) -> __sdk::__query_builder::Table<GroundLoot>;
}

impl ground_lootQueryTableAccess for __sdk::QueryTableAccessor {
    fn ground_loot(&self) -> __sdk::__query_builder::Table<GroundLoot> {
        __sdk::__query_builder::Table::new("ground_loot")
    }
}
