// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HarvestableCorpse {
    pub entity_id: u64,
    pub loot_item: String,
    pub amount: u32,
}

impl __sdk::InModule for HarvestableCorpse {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HarvestableCorpse`.
///
/// Provides typed access to columns for query building.
pub struct HarvestableCorpseCols {
    pub entity_id: __sdk::__query_builder::Col<HarvestableCorpse, u64>,
    pub loot_item: __sdk::__query_builder::Col<HarvestableCorpse, String>,
    pub amount: __sdk::__query_builder::Col<HarvestableCorpse, u32>,
}

impl __sdk::__query_builder::HasCols for HarvestableCorpse {
    type Cols = HarvestableCorpseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HarvestableCorpseCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            loot_item: __sdk::__query_builder::Col::new(table_name, "loot_item"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
        }
    }
}

/// Indexed column accessor struct for the table `HarvestableCorpse`.
///
/// Provides typed access to indexed columns for query building.
pub struct HarvestableCorpseIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<HarvestableCorpse, u64>,
}

impl __sdk::__query_builder::HasIxCols for HarvestableCorpse {
    type IxCols = HarvestableCorpseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HarvestableCorpseIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for HarvestableCorpse {}
