// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::health_type::Health;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `health`.
///
/// Obtain a handle from the [`HealthTableAccess::health`] method on [`super::RemoteTables`],
/// like `ctx.db.health()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.health().on_insert(...)`.
pub struct HealthTableHandle<'ctx> {
    imp: __sdk::TableHandle<Health>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `health`.
pub struct HealthTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for HealthTableAccessor {
    type Row = Health;
    type Handle<'db> = HealthTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.health()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `health`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HealthTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HealthTableHandle`], which mediates access to the table `health`.
    fn health(&self) -> HealthTableHandle<'_>;
}

impl HealthTableAccess for super::RemoteTables {
    fn health(&self) -> HealthTableHandle<'_> {
        HealthTableHandle {
            imp: self.imp.get_table::<Health>("health"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HealthInsertCallbackId(__sdk::CallbackId);
pub struct HealthDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for HealthTableHandle<'ctx> {
    type Row = Health;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Health> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for HealthTableHandle<'ctx> {
    type Row = Health;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Health> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HealthInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HealthInsertCallbackId {
        HealthInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HealthInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HealthDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HealthDeleteCallbackId {
        HealthDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HealthDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for HealthTableHandle<'ctx> {
    type InsertCallbackId = HealthInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HealthInsertCallbackId {
        HealthInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HealthInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for HealthTableHandle<'ctx> {
    type DeleteCallbackId = HealthDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HealthDeleteCallbackId {
        HealthDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HealthDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct HealthUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for HealthTableHandle<'ctx> {
    type UpdateCallbackId = HealthUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HealthUpdateCallbackId {
        HealthUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HealthUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for HealthTableHandle<'ctx> {
    type UpdateCallbackId = HealthUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HealthUpdateCallbackId {
        HealthUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HealthUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `health`,
/// which allows point queries on the field of the same name
/// via the [`HealthEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.health().entity_id().find(...)`.
pub struct HealthEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Health, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> HealthTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `health`.
    pub fn entity_id(&self) -> HealthEntityIdUnique<'ctx> {
        HealthEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> HealthEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Health> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Health>("health");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Health>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Health>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Health`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait healthQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Health`.
    fn health(&self) -> __sdk::__query_builder::Table<Health>;
}

impl healthQueryTableAccess for __sdk::QueryTableAccessor {
    fn health(&self) -> __sdk::__query_builder::Table<Health> {
        __sdk::__query_builder::Table::new("health")
    }
}
