// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::inventory_slot_type::InventorySlot;
use super::inventory_type::Inventory;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `inventory`.
///
/// Obtain a handle from the [`InventoryTableAccess::inventory`] method on [`super::RemoteTables`],
/// like `ctx.db.inventory()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inventory().on_insert(...)`.
pub struct InventoryTableHandle<'ctx> {
    imp: __sdk::TableHandle<Inventory>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `inventory`.
pub struct InventoryTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for InventoryTableAccessor {
    type Row = Inventory;
    type Handle<'db> = InventoryTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.inventory()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `inventory`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InventoryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InventoryTableHandle`], which mediates access to the table `inventory`.
    fn inventory(&self) -> InventoryTableHandle<'_>;
}

impl InventoryTableAccess for super::RemoteTables {
    fn inventory(&self) -> InventoryTableHandle<'_> {
        InventoryTableHandle {
            imp: self.imp.get_table::<Inventory>("inventory"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InventoryInsertCallbackId(__sdk::CallbackId);
pub struct InventoryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for InventoryTableHandle<'ctx> {
    type Row = Inventory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Inventory> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for InventoryTableHandle<'ctx> {
    type Row = Inventory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Inventory> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InventoryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InventoryInsertCallbackId {
        InventoryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InventoryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InventoryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InventoryDeleteCallbackId {
        InventoryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InventoryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for InventoryTableHandle<'ctx> {
    type InsertCallbackId = InventoryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InventoryInsertCallbackId {
        InventoryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InventoryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for InventoryTableHandle<'ctx> {
    type DeleteCallbackId = InventoryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InventoryDeleteCallbackId {
        InventoryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InventoryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InventoryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InventoryTableHandle<'ctx> {
    type UpdateCallbackId = InventoryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InventoryUpdateCallbackId {
        InventoryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InventoryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for InventoryTableHandle<'ctx> {
    type UpdateCallbackId = InventoryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InventoryUpdateCallbackId {
        InventoryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InventoryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `inventory`,
/// which allows point queries on the field of the same name
/// via the [`InventoryEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inventory().entity_id().find(...)`.
pub struct InventoryEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Inventory, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InventoryTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `inventory`.
    pub fn entity_id(&self) -> InventoryEntityIdUnique<'ctx> {
        InventoryEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InventoryEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Inventory> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Inventory>("inventory");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Inventory>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Inventory>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Inventory`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait inventoryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Inventory`.
    fn inventory(&self) -> __sdk::__query_builder::Table<Inventory>;
}

impl inventoryQueryTableAccess for __sdk::QueryTableAccessor {
    fn inventory(&self) -> __sdk::__query_builder::Table<Inventory> {
        __sdk::__query_builder::Table::new("inventory")
    }
}
