// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ai_type_type::AiType;
use super::brain_state_type::BrainState;
use super::npc_brain_type::NpcBrain;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_brain`.
///
/// Obtain a handle from the [`NpcBrainTableAccess::npc_brain`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_brain()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_brain().on_insert(...)`.
pub struct NpcBrainTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcBrain>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `npc_brain`.
pub struct NpcBrainTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for NpcBrainTableAccessor {
    type Row = NpcBrain;
    type Handle<'db> = NpcBrainTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.npc_brain()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_brain`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcBrainTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcBrainTableHandle`], which mediates access to the table `npc_brain`.
    fn npc_brain(&self) -> NpcBrainTableHandle<'_>;
}

impl NpcBrainTableAccess for super::RemoteTables {
    fn npc_brain(&self) -> NpcBrainTableHandle<'_> {
        NpcBrainTableHandle {
            imp: self.imp.get_table::<NpcBrain>("npc_brain"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcBrainInsertCallbackId(__sdk::CallbackId);
pub struct NpcBrainDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for NpcBrainTableHandle<'ctx> {
    type Row = NpcBrain;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcBrain> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for NpcBrainTableHandle<'ctx> {
    type Row = NpcBrain;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcBrain> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcBrainInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcBrainInsertCallbackId {
        NpcBrainInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcBrainInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcBrainDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcBrainDeleteCallbackId {
        NpcBrainDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcBrainDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for NpcBrainTableHandle<'ctx> {
    type InsertCallbackId = NpcBrainInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcBrainInsertCallbackId {
        NpcBrainInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcBrainInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for NpcBrainTableHandle<'ctx> {
    type DeleteCallbackId = NpcBrainDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcBrainDeleteCallbackId {
        NpcBrainDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcBrainDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NpcBrainUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcBrainTableHandle<'ctx> {
    type UpdateCallbackId = NpcBrainUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcBrainUpdateCallbackId {
        NpcBrainUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcBrainUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for NpcBrainTableHandle<'ctx> {
    type UpdateCallbackId = NpcBrainUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcBrainUpdateCallbackId {
        NpcBrainUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcBrainUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `npc_brain`,
/// which allows point queries on the field of the same name
/// via the [`NpcBrainEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_brain().entity_id().find(...)`.
pub struct NpcBrainEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcBrain, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcBrainTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `npc_brain`.
    pub fn entity_id(&self) -> NpcBrainEntityIdUnique<'ctx> {
        NpcBrainEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcBrainEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NpcBrain> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcBrain>("npc_brain");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NpcBrain>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcBrain>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NpcBrain`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait npc_brainQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NpcBrain`.
    fn npc_brain(&self) -> __sdk::__query_builder::Table<NpcBrain>;
}

impl npc_brainQueryTableAccess for __sdk::QueryTableAccessor {
    fn npc_brain(&self) -> __sdk::__query_builder::Table<NpcBrain> {
        __sdk::__query_builder::Table::new("npc_brain")
    }
}
