// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ai_state_type::AiState;
use super::peasant_type::Peasant;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `peasant`.
///
/// Obtain a handle from the [`PeasantTableAccess::peasant`] method on [`super::RemoteTables`],
/// like `ctx.db.peasant()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.peasant().on_insert(...)`.
pub struct PeasantTableHandle<'ctx> {
    imp: __sdk::TableHandle<Peasant>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `peasant`.
pub struct PeasantTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PeasantTableAccessor {
    type Row = Peasant;
    type Handle<'db> = PeasantTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.peasant()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `peasant`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PeasantTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PeasantTableHandle`], which mediates access to the table `peasant`.
    fn peasant(&self) -> PeasantTableHandle<'_>;
}

impl PeasantTableAccess for super::RemoteTables {
    fn peasant(&self) -> PeasantTableHandle<'_> {
        PeasantTableHandle {
            imp: self.imp.get_table::<Peasant>("peasant"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PeasantInsertCallbackId(__sdk::CallbackId);
pub struct PeasantDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PeasantTableHandle<'ctx> {
    type Row = Peasant;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Peasant> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PeasantTableHandle<'ctx> {
    type Row = Peasant;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Peasant> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PeasantInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PeasantInsertCallbackId {
        PeasantInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PeasantInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PeasantDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PeasantDeleteCallbackId {
        PeasantDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PeasantDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PeasantTableHandle<'ctx> {
    type InsertCallbackId = PeasantInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PeasantInsertCallbackId {
        PeasantInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PeasantInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PeasantTableHandle<'ctx> {
    type DeleteCallbackId = PeasantDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PeasantDeleteCallbackId {
        PeasantDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PeasantDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PeasantUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PeasantTableHandle<'ctx> {
    type UpdateCallbackId = PeasantUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PeasantUpdateCallbackId {
        PeasantUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PeasantUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PeasantTableHandle<'ctx> {
    type UpdateCallbackId = PeasantUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PeasantUpdateCallbackId {
        PeasantUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PeasantUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `peasant`,
/// which allows point queries on the field of the same name
/// via the [`PeasantEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.peasant().entity_id().find(...)`.
pub struct PeasantEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Peasant, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PeasantTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `peasant`.
    pub fn entity_id(&self) -> PeasantEntityIdUnique<'ctx> {
        PeasantEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PeasantEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Peasant> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Peasant>("peasant");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Peasant>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Peasant>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Peasant`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait peasantQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Peasant`.
    fn peasant(&self) -> __sdk::__query_builder::Table<Peasant>;
}

impl peasantQueryTableAccess for __sdk::QueryTableAccessor {
    fn peasant(&self) -> __sdk::__query_builder::Table<Peasant> {
        __sdk::__query_builder::Table::new("peasant")
    }
}
