// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerSession {
    pub identity: __sdk::Identity,
    pub entity_id: u64,
}

impl __sdk::InModule for PlayerSession {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerSession`.
///
/// Provides typed access to columns for query building.
pub struct PlayerSessionCols {
    pub identity: __sdk::__query_builder::Col<PlayerSession, __sdk::Identity>,
    pub entity_id: __sdk::__query_builder::Col<PlayerSession, u64>,
}

impl __sdk::__query_builder::HasCols for PlayerSession {
    type Cols = PlayerSessionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerSessionCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerSession`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerSessionIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PlayerSession, u64>,
    pub identity: __sdk::__query_builder::IxCol<PlayerSession, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for PlayerSession {
    type IxCols = PlayerSessionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerSessionIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerSession {}
