// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_session_type::PlayerSession;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_session`.
///
/// Obtain a handle from the [`PlayerSessionTableAccess::player_session`] method on [`super::RemoteTables`],
/// like `ctx.db.player_session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_session().on_insert(...)`.
pub struct PlayerSessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerSession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `player_session`.
pub struct PlayerSessionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PlayerSessionTableAccessor {
    type Row = PlayerSession;
    type Handle<'db> = PlayerSessionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.player_session()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerSessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerSessionTableHandle`], which mediates access to the table `player_session`.
    fn player_session(&self) -> PlayerSessionTableHandle<'_>;
}

impl PlayerSessionTableAccess for super::RemoteTables {
    fn player_session(&self) -> PlayerSessionTableHandle<'_> {
        PlayerSessionTableHandle {
            imp: self.imp.get_table::<PlayerSession>("player_session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerSessionInsertCallbackId(__sdk::CallbackId);
pub struct PlayerSessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PlayerSessionTableHandle<'ctx> {
    type Row = PlayerSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerSession> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PlayerSessionTableHandle<'ctx> {
    type Row = PlayerSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerSession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerSessionInsertCallbackId {
        PlayerSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerSessionDeleteCallbackId {
        PlayerSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PlayerSessionTableHandle<'ctx> {
    type InsertCallbackId = PlayerSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerSessionInsertCallbackId {
        PlayerSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PlayerSessionTableHandle<'ctx> {
    type DeleteCallbackId = PlayerSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerSessionDeleteCallbackId {
        PlayerSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlayerSessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerSessionTableHandle<'ctx> {
    type UpdateCallbackId = PlayerSessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerSessionUpdateCallbackId {
        PlayerSessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerSessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PlayerSessionTableHandle<'ctx> {
    type UpdateCallbackId = PlayerSessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerSessionUpdateCallbackId {
        PlayerSessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerSessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `player_session`,
/// which allows point queries on the field of the same name
/// via the [`PlayerSessionIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_session().identity().find(...)`.
pub struct PlayerSessionIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerSession, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerSessionTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `player_session`.
    pub fn identity(&self) -> PlayerSessionIdentityUnique<'ctx> {
        PlayerSessionIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerSessionIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PlayerSession> {
        self.imp.find(col_val)
    }
}

/// Access to the `entity_id` unique index on the table `player_session`,
/// which allows point queries on the field of the same name
/// via the [`PlayerSessionEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_session().entity_id().find(...)`.
pub struct PlayerSessionEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerSession, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerSessionTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `player_session`.
    pub fn entity_id(&self) -> PlayerSessionEntityIdUnique<'ctx> {
        PlayerSessionEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerSessionEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PlayerSession> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerSession>("player_session");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerSession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerSession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerSession`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait player_sessionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerSession`.
    fn player_session(&self) -> __sdk::__query_builder::Table<PlayerSession>;
}

impl player_sessionQueryTableAccess for __sdk::QueryTableAccessor {
    fn player_session(&self) -> __sdk::__query_builder::Table<PlayerSession> {
        __sdk::__query_builder::Table::new("player_session")
    }
}
