// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_identity_type::PlayerIdentity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_identity`.
///
/// Obtain a handle from the [`PlayerIdentityTableAccess::player_identity`] method on [`super::RemoteTables`],
/// like `ctx.db.player_identity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_identity().on_insert(...)`.
pub struct PlayerIdentityTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerIdentity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `player_identity`.
pub struct PlayerIdentityTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PlayerIdentityTableAccessor {
    type Row = PlayerIdentity;
    type Handle<'db> = PlayerIdentityTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.player_identity()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_identity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerIdentityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerIdentityTableHandle`], which mediates access to the table `player_identity`.
    fn player_identity(&self) -> PlayerIdentityTableHandle<'_>;
}

impl PlayerIdentityTableAccess for super::RemoteTables {
    fn player_identity(&self) -> PlayerIdentityTableHandle<'_> {
        PlayerIdentityTableHandle {
            imp: self.imp.get_table::<PlayerIdentity>("player_identity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerIdentityInsertCallbackId(__sdk::CallbackId);
pub struct PlayerIdentityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PlayerIdentityTableHandle<'ctx> {
    type Row = PlayerIdentity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerIdentity> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PlayerIdentityTableHandle<'ctx> {
    type Row = PlayerIdentity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerIdentity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerIdentityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerIdentityInsertCallbackId {
        PlayerIdentityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerIdentityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerIdentityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerIdentityDeleteCallbackId {
        PlayerIdentityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerIdentityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PlayerIdentityTableHandle<'ctx> {
    type InsertCallbackId = PlayerIdentityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerIdentityInsertCallbackId {
        PlayerIdentityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerIdentityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PlayerIdentityTableHandle<'ctx> {
    type DeleteCallbackId = PlayerIdentityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerIdentityDeleteCallbackId {
        PlayerIdentityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerIdentityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlayerIdentityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerIdentityTableHandle<'ctx> {
    type UpdateCallbackId = PlayerIdentityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerIdentityUpdateCallbackId {
        PlayerIdentityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerIdentityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PlayerIdentityTableHandle<'ctx> {
    type UpdateCallbackId = PlayerIdentityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerIdentityUpdateCallbackId {
        PlayerIdentityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerIdentityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `player_identity`,
/// which allows point queries on the field of the same name
/// via the [`PlayerIdentityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_identity().id().find(...)`.
pub struct PlayerIdentityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerIdentity, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerIdentityTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `player_identity`.
    pub fn id(&self) -> PlayerIdentityIdUnique<'ctx> {
        PlayerIdentityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerIdentityIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PlayerIdentity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerIdentity>("player_identity");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerIdentity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerIdentity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerIdentity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait player_identityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerIdentity`.
    fn player_identity(&self) -> __sdk::__query_builder::Table<PlayerIdentity>;
}

impl player_identityQueryTableAccess for __sdk::QueryTableAccessor {
    fn player_identity(&self) -> __sdk::__query_builder::Table<PlayerIdentity> {
        __sdk::__query_builder::Table::new("player_identity")
    }
}
