// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::structure_type::Structure;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `structure`.
///
/// Obtain a handle from the [`StructureTableAccess::structure`] method on [`super::RemoteTables`],
/// like `ctx.db.structure()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.structure().on_insert(...)`.
pub struct StructureTableHandle<'ctx> {
    imp: __sdk::TableHandle<Structure>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `structure`.
pub struct StructureTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for StructureTableAccessor {
    type Row = Structure;
    type Handle<'db> = StructureTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.structure()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `structure`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StructureTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StructureTableHandle`], which mediates access to the table `structure`.
    fn structure(&self) -> StructureTableHandle<'_>;
}

impl StructureTableAccess for super::RemoteTables {
    fn structure(&self) -> StructureTableHandle<'_> {
        StructureTableHandle {
            imp: self.imp.get_table::<Structure>("structure"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StructureInsertCallbackId(__sdk::CallbackId);
pub struct StructureDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for StructureTableHandle<'ctx> {
    type Row = Structure;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Structure> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for StructureTableHandle<'ctx> {
    type Row = Structure;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Structure> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StructureInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StructureInsertCallbackId {
        StructureInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StructureInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StructureDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StructureDeleteCallbackId {
        StructureDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StructureDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for StructureTableHandle<'ctx> {
    type InsertCallbackId = StructureInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StructureInsertCallbackId {
        StructureInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StructureInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for StructureTableHandle<'ctx> {
    type DeleteCallbackId = StructureDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StructureDeleteCallbackId {
        StructureDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StructureDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct StructureUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StructureTableHandle<'ctx> {
    type UpdateCallbackId = StructureUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StructureUpdateCallbackId {
        StructureUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StructureUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for StructureTableHandle<'ctx> {
    type UpdateCallbackId = StructureUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StructureUpdateCallbackId {
        StructureUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StructureUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `structure_id` unique index on the table `structure`,
/// which allows point queries on the field of the same name
/// via the [`StructureStructureIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.structure().structure_id().find(...)`.
pub struct StructureStructureIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Structure, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StructureTableHandle<'ctx> {
    /// Get a handle on the `structure_id` unique index on the table `structure`.
    pub fn structure_id(&self) -> StructureStructureIdUnique<'ctx> {
        StructureStructureIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("structure_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StructureStructureIdUnique<'ctx> {
    /// Find the subscribed row whose `structure_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Structure> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Structure>("structure");
    _table.add_unique_constraint::<u64>("structure_id", |row| &row.structure_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Structure>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Structure>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Structure`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait structureQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Structure`.
    fn structure(&self) -> __sdk::__query_builder::Table<Structure>;
}

impl structureQueryTableAccess for __sdk::QueryTableAccessor {
    fn structure(&self) -> __sdk::__query_builder::Table<Structure> {
        __sdk::__query_builder::Table::new("structure")
    }
}
