// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Transform {
    pub player_id: u64,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
    pub pitch: f32,
    pub timestamp: u64,
}

impl __sdk::InModule for Transform {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Transform`.
///
/// Provides typed access to columns for query building.
pub struct TransformCols {
    pub player_id: __sdk::__query_builder::Col<Transform, u64>,
    pub x: __sdk::__query_builder::Col<Transform, f32>,
    pub y: __sdk::__query_builder::Col<Transform, f32>,
    pub z: __sdk::__query_builder::Col<Transform, f32>,
    pub yaw: __sdk::__query_builder::Col<Transform, f32>,
    pub pitch: __sdk::__query_builder::Col<Transform, f32>,
    pub timestamp: __sdk::__query_builder::Col<Transform, u64>,
}

impl __sdk::__query_builder::HasCols for Transform {
    type Cols = TransformCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TransformCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            pitch: __sdk::__query_builder::Col::new(table_name, "pitch"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
        }
    }
}

/// Indexed column accessor struct for the table `Transform`.
///
/// Provides typed access to indexed columns for query building.
pub struct TransformIxCols {
    pub player_id: __sdk::__query_builder::IxCol<Transform, u64>,
}

impl __sdk::__query_builder::HasIxCols for Transform {
    type IxCols = TransformIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TransformIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Transform {}
